import jsPDF from "jspdf";
import type { UVPRSResult } from "@/lib/uvprs-scoring";
import type { TCOResult } from "@/lib/tco-calculations";

interface VehicleData {
  year: number;
  make: string;
  model: string;
  trim?: string;
  mileage: number;
  askingPrice: number;
}

interface PriceAssessment {
  fairMarketPrivate: number;
  fairMarketDealer?: number;
  fairMarketTradeIn: number;
  dealRating: string;
  priceDifference: number;
}

interface RiskAssessment {
  level: string;
  fairOfferPrice: number;
  expertOpinion: string;
  depreciationRisk: string;
  reliabilityConcerns: string[];
  valueProposition?: string;
}

interface HistoryAnalysis {
  healthScore: number;
  positives: string[];
  concerns: string[];
}

interface DepreciationRow {
  year: number;
  privateValue: number;
  tradeInValue: number;
  loanBalance: number;
  repairCosts: number;
}

interface DealerReview {
  dealerName: string;
  trustScore: number;
  sentiment: "positive" | "mixed" | "negative" | "unknown";
  summary: string;
  positives: string[];
  watchOuts: string[];
  sources: string[];
}

interface ServiceHistory {
  serviceGapMiles?: number | null;
  majorServicesDue?: string[] | null;
  majorServicesDone?: string[] | null;
  chronicRepairSystems?: string[] | null;
}

interface TCOData {
  tco: TCOResult;
  annualMiles: number;
  gasPricePerGallon?: number;
  electricityPerKwh?: number;
}

interface ReportData {
  vehicle: VehicleData;
  priceAssessment: PriceAssessment;
  riskAssessment: RiskAssessment;
  historyAnalysis: HistoryAnalysis;
  depreciationTable: DepreciationRow[];
  images?: string[];
  dealerReview?: DealerReview;
  serviceHistory?: ServiceHistory;
  uvprsResult?: UVPRSResult;
  tcoData?: TCOData;
  sellerType?: string;
}

// ── Color palette matching the website ──
// Primary teal: hsl(174, 72%, 40%) ≈ rgb(28, 175, 154)
const TEAL: [number, number, number] = [28, 175, 154];
const TEAL_LIGHT: [number, number, number] = [232, 248, 245]; // bg tint
const GREEN: [number, number, number] = [34, 197, 94];
const AMBER: [number, number, number] = [234, 179, 8];
const RED: [number, number, number] = [220, 38, 38];
const ORANGE: [number, number, number] = [249, 115, 22];
const SLATE: [number, number, number] = [100, 116, 139];
const BG_MUTED: [number, number, number] = [241, 245, 249];
const BLACK: [number, number, number] = [15, 23, 42];
const WHITE: [number, number, number] = [255, 255, 255];

// Helper to load image as base64 for PDF
async function loadImageAsBase64(url: string): Promise<string | null> {
  try {
    const response = await fetch(url, { mode: "cors" });
    if (!response.ok) return null;
    const blob = await response.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

function fitImageToBox(
  imgWidth: number,
  imgHeight: number,
  maxWidth: number,
  maxHeight: number
): { width: number; height: number } {
  const ratio = Math.min(maxWidth / imgWidth, maxHeight / imgHeight);
  return { width: imgWidth * ratio, height: imgHeight * ratio };
}

const fmt = (v: number) => `$${v.toLocaleString()}`;

export async function generateReportPDF(data: ReportData): Promise<void> {
  const pdf = new jsPDF("p", "mm", "a4");
  const W = pdf.internal.pageSize.getWidth();
  const H = pdf.internal.pageSize.getHeight();
  const M = 14; // margin
  const contentW = W - 2 * M;
  let y = 0;

  const { vehicle, priceAssessment, riskAssessment, historyAnalysis, depreciationTable, images, dealerReview, serviceHistory, uvprsResult, tcoData, sellerType } = data;

  // ── Helpers ──
  const ensureSpace = (needed: number) => {
    if (y + needed > H - 12) {
      addFooter();
      pdf.addPage();
      y = M;
    }
  };

  const addFooter = () => {
    pdf.setFontSize(7);
    pdf.setTextColor(...SLATE);
    pdf.text(`Generated by CarWise on ${new Date().toLocaleDateString()}`, M, H - 6);
    pdf.text("www.carwise.com", W - M - 28, H - 6);
  };

  const sectionTitle = (icon: string, title: string) => {
    ensureSpace(14);
    y += 6;
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(...TEAL);
    pdf.text(`${icon}  ${title}`, M, y);
    y += 6;
  };

  const wrappedText = (text: string, fontSize: number, color: [number, number, number] = BLACK, bold = false, indent = 0) => {
    pdf.setFontSize(fontSize);
    pdf.setFont("helvetica", bold ? "bold" : "normal");
    pdf.setTextColor(...color);
    const lines = pdf.splitTextToSize(text, contentW - indent);
    const lh = fontSize * 0.4;
    ensureSpace(lines.length * lh + 2);
    pdf.text(lines, M + indent, y);
    y += lines.length * lh + 1.5;
  };

  // ══════════════════════════════════════════════
  // HEADER — Teal banner with CarWise branding
  // ══════════════════════════════════════════════
  pdf.setFillColor(...TEAL);
  pdf.rect(0, 0, W, 28, "F");

  // Car icon (unicode car)
  pdf.setTextColor(...WHITE);
  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.text("CarWise", M, 14);
  // Subtitle
  pdf.setFontSize(9);
  pdf.setFont("helvetica", "normal");
  pdf.text("Vehicle Analysis Report", M, 21);
  // Date on right
  pdf.setFontSize(8);
  pdf.text(new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" }), W - M - 40, 14);

  y = 36;

  // ══════════════════════════════════════════════
  // VEHICLE TITLE
  // ══════════════════════════════════════════════
  pdf.setFontSize(18);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(...BLACK);
  pdf.text(`${vehicle.year} ${vehicle.make} ${vehicle.model}${vehicle.trim ? ` ${vehicle.trim}` : ""}`, M, y);
  y += 6;
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(...SLATE);
  pdf.text(`${vehicle.mileage.toLocaleString()} miles  •  Asking ${fmt(vehicle.askingPrice)}`, M, y);
  y += 8;

  // ══════════════════════════════════════════════
  // QUICK STATS (4 cards in a row matching the website)
  // ══════════════════════════════════════════════
  const cardW = (contentW - 9) / 4;
  const cardH = 22;

  const referenceValue = sellerType === "dealer" && priceAssessment.fairMarketDealer
    ? priceAssessment.fairMarketDealer
    : priceAssessment.fairMarketPrivate;

  const ratingColor = (r: string): [number, number, number] => {
    const map: Record<string, [number, number, number]> = {
      excellent: GREEN, good: GREEN, fair: AMBER, poor: ORANGE, overpriced: RED,
    };
    return map[r] || BLACK;
  };

  const uvprsColor = (): [number, number, number] => {
    if (!uvprsResult) return SLATE;
    return uvprsResult.riskLevel === "low" ? GREEN : uvprsResult.riskLevel === "moderate" ? AMBER : RED;
  };

  const cards = [
    { label: sellerType === "dealer" ? "Dealer Retail Value" : "Private Sale Value", value: fmt(referenceValue), color: TEAL },
    { label: "Deal Rating", value: priceAssessment.dealRating.charAt(0).toUpperCase() + priceAssessment.dealRating.slice(1), color: ratingColor(priceAssessment.dealRating) },
    { label: "Risk Score", value: uvprsResult ? `${uvprsResult.totalScore} / 100` : riskAssessment.level, color: uvprsColor() },
    { label: "Fair Offer", value: fmt(riskAssessment.fairOfferPrice), color: GREEN },
  ];

  cards.forEach((card, i) => {
    const x = M + i * (cardW + 3);
    pdf.setFillColor(...BG_MUTED);
    pdf.roundedRect(x, y, cardW, cardH, 2, 2, "F");
    // Color dot
    pdf.setFillColor(...card.color);
    pdf.circle(x + 6, y + cardH / 2, 3, "F");
    // Label
    pdf.setFontSize(7);
    pdf.setTextColor(...SLATE);
    pdf.text(card.label, x + 12, y + 8);
    // Value
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(...card.color);
    pdf.text(card.value, x + 12, y + 16);
    pdf.setFont("helvetica", "normal");
  });

  y += cardH + 8;

  // ══════════════════════════════════════════════
  // VEHICLE IMAGES (2x2 grid)
  // ══════════════════════════════════════════════
  if (images && images.length > 0) {
    const imagesToLoad = images.slice(0, 4);
    const loadedImages: { base64: string; width: number; height: number }[] = [];

    await Promise.all(
      imagesToLoad.map(async (url) => {
        const base64 = await loadImageAsBase64(url);
        if (base64) {
          const img = new Image();
          await new Promise<void>((resolve) => {
            img.onload = () => {
              loadedImages.push({ base64, width: img.width, height: img.height });
              resolve();
            };
            img.onerror = () => resolve();
            img.src = base64;
          });
        }
      })
    );

    if (loadedImages.length > 0) {
      const gridCols = Math.min(2, loadedImages.length);
      const imgBoxWidth = (contentW - 4) / gridCols;
      const imgBoxHeight = 35;
      const totalRows = Math.ceil(loadedImages.length / 2);
      ensureSpace(totalRows * (imgBoxHeight + 3) + 2);

      loadedImages.forEach((imgData, index) => {
        const col = index % 2;
        const row = Math.floor(index / 2);
        const xPos = M + col * (imgBoxWidth + 4);
        const yPos = y + row * (imgBoxHeight + 3);

        pdf.setFillColor(...BG_MUTED);
        pdf.roundedRect(xPos, yPos, imgBoxWidth, imgBoxHeight, 2, 2, "F");

        const padding = 2;
        const fitted = fitImageToBox(imgData.width, imgData.height, imgBoxWidth - padding * 2, imgBoxHeight - padding * 2);
        const imgX = xPos + (imgBoxWidth - fitted.width) / 2;
        const imgY = yPos + (imgBoxHeight - fitted.height) / 2;
        try {
          pdf.addImage(imgData.base64, "JPEG", imgX, imgY, fitted.width, fitted.height);
        } catch { /* skip */ }
      });

      y += totalRows * (imgBoxHeight + 3) + 4;
    }
  }

  // ══════════════════════════════════════════════
  // PRICE ASSESSMENT
  // ══════════════════════════════════════════════
  sectionTitle("$", "Price Assessment");

  // Asking vs Fair Market highlight box
  ensureSpace(22);
  pdf.setFillColor(...BG_MUTED);
  pdf.roundedRect(M, y, contentW, 18, 3, 3, "F");
  pdf.setFontSize(8);
  pdf.setTextColor(...SLATE);
  pdf.text("Asking Price", M + 5, y + 6);
  pdf.setFontSize(13);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(...BLACK);
  pdf.text(fmt(vehicle.askingPrice), M + 5, y + 13);

  pdf.setFontSize(8);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(...SLATE);
  pdf.text("vs Fair Market", W - M - 45, y + 6);
  const diffColor: [number, number, number] = priceAssessment.priceDifference > 0 ? RED : GREEN;
  pdf.setFontSize(13);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(...diffColor);
  pdf.text(`${priceAssessment.priceDifference > 0 ? "+" : ""}${fmt(Math.abs(priceAssessment.priceDifference))}`, W - M - 45, y + 13);
  y += 22;

  // Price breakdown cards
  const priceCards = [
    { label: "Private Sale", value: fmt(priceAssessment.fairMarketPrivate) },
    { label: "Trade-In Value", value: fmt(priceAssessment.fairMarketTradeIn) },
  ];
  if (priceAssessment.fairMarketDealer) {
    priceCards.unshift({ label: "Dealer Retail", value: fmt(priceAssessment.fairMarketDealer) });
  }
  const pcW = (contentW - (priceCards.length - 1) * 3) / priceCards.length;
  ensureSpace(18);
  priceCards.forEach((pc, i) => {
    const x = M + i * (pcW + 3);
    pdf.setDrawColor(200, 210, 220);
    pdf.roundedRect(x, y, pcW, 14, 2, 2, "S");
    pdf.setFontSize(7);
    pdf.setTextColor(...SLATE);
    pdf.text(pc.label, x + 4, y + 5);
    pdf.setFontSize(11);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(...BLACK);
    pdf.text(pc.value, x + 4, y + 11);
    pdf.setFont("helvetica", "normal");
  });
  y += 18;

  // ══════════════════════════════════════════════
  // FUEL ECONOMY & TOTAL COST OF OWNERSHIP
  // ══════════════════════════════════════════════
  if (tcoData) {
    const { tco, annualMiles } = tcoData;
    sectionTitle("⛽", `Fuel Economy & Ownership Cost (${annualMiles.toLocaleString()} mi/yr)`);

    // TCO summary box
    ensureSpace(24);
    pdf.setFillColor(...BG_MUTED);
    pdf.roundedRect(M, y, contentW, 20, 3, 3, "F");

    const tcoColW = contentW / 3;
    const items = [
      { label: "Total 5-Year Cost", value: fmt(tco.totalTCO), color: RED },
      { label: "Cost Per Mile", value: `$${tco.costPerMile.toFixed(2)}`, color: RED },
      { label: "Monthly Ownership", value: `${fmt(Math.round((tco.annualFuelCost / 12) + (tco.repairCost5Year / 60)))}/mo`, color: BLACK },
    ];
    items.forEach((item, i) => {
      const x = M + i * tcoColW + 5;
      pdf.setFontSize(7);
      pdf.setTextColor(...SLATE);
      pdf.text(item.label, x, y + 7);
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(...item.color);
      pdf.text(item.value, x, y + 15);
      pdf.setFont("helvetica", "normal");
    });
    y += 24;

    // TCO Breakdown table
    const breakdownItems: [string, number][] = [
      ["Purchase Price", tco.purchasePrice],
      [`5-Year ${tco.fuelCost5Year > 0 ? "Fuel" : "Energy"} Cost`, tco.fuelCost5Year],
      ["5-Year Maintenance", tco.repairCost5Year],
    ];
    if (tco.mileageDepreciation && tco.mileageDepreciation > 0) {
      breakdownItems.push(["Excess Mileage Depreciation", tco.mileageDepreciation]);
    }

    ensureSpace(breakdownItems.length * 7 + 14);
    // Header
    pdf.setFillColor(...TEAL);
    pdf.rect(M, y, contentW, 7, "F");
    pdf.setTextColor(...WHITE);
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "bold");
    pdf.text("Category", M + 3, y + 5);
    pdf.text("Amount", M + contentW - 35, y + 5);
    y += 9;

    breakdownItems.forEach(([label, amount], idx) => {
      if (idx % 2 === 0) {
        pdf.setFillColor(...BG_MUTED);
        pdf.rect(M, y - 3, contentW, 7, "F");
      }
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(9);
      pdf.setTextColor(...BLACK);
      pdf.text(label, M + 3, y);
      pdf.setFont("helvetica", "bold");
      pdf.text(fmt(amount), M + contentW - 35, y);
      y += 7;
    });

    // Total row
    pdf.setFillColor(...TEAL);
    pdf.rect(M, y - 3, contentW, 8, "F");
    pdf.setTextColor(...WHITE);
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "bold");
    pdf.text("Total Cost of Ownership", M + 3, y + 1);
    pdf.text(fmt(tco.totalTCO), M + contentW - 35, y + 1);
    y += 12;

    // Footnotes
    pdf.setFontSize(7);
    pdf.setTextColor(...SLATE);
    pdf.text(`Based on ${annualMiles.toLocaleString()} miles/year over 5 years.`, M, y);
    y += 4;
    if (tco.mileageDepreciation && tco.mileageDepreciation > 0) {
      pdf.text("Excess mileage depreciation: ~$0.18/mile above 12,000 mi/yr baseline.", M, y);
      y += 4;
    }
  }

  // ══════════════════════════════════════════════
  // UVPRS RISK SCORE BREAKDOWN
  // ══════════════════════════════════════════════
  if (uvprsResult) {
    sectionTitle("🛡", "Purchase Risk Score (UVPRS)");

    // Score header box
    ensureSpace(20);
    pdf.setFillColor(...BG_MUTED);
    pdf.roundedRect(M, y, contentW, 16, 3, 3, "F");

    const scoreColor = uvprsResult.riskLevel === "low" ? GREEN : uvprsResult.riskLevel === "moderate" ? AMBER : RED;
    pdf.setFontSize(18);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(...scoreColor);
    pdf.text(`${uvprsResult.totalScore}`, M + 5, y + 10);
    pdf.setFontSize(9);
    pdf.setTextColor(...SLATE);
    pdf.text("/ 100", M + 22, y + 10);
    // Risk label badge
    pdf.setFillColor(...scoreColor);
    pdf.roundedRect(M + 38, y + 4, 30, 8, 2, 2, "F");
    pdf.setFontSize(7);
    pdf.setTextColor(...WHITE);
    pdf.text(uvprsResult.riskLabel, M + 41, y + 9);
    // Known factors
    pdf.setTextColor(...SLATE);
    pdf.setFontSize(7);
    pdf.text(`${uvprsResult.knownFactorCount} of ${uvprsResult.factors.length} factors verified`, M + 75, y + 10);
    y += 20;

    // Factor breakdown table
    const factorColWidths = [52, 18, 18, contentW - 88];
    const factorHeaders = ["Factor", "Weight", "Score", "Detail"];

    ensureSpace(uvprsResult.factors.length * 7 + 12);
    pdf.setFillColor(...TEAL);
    pdf.rect(M, y, contentW, 7, "F");
    pdf.setTextColor(...WHITE);
    pdf.setFontSize(7);
    pdf.setFont("helvetica", "bold");
    let fxPos = M;
    factorHeaders.forEach((h, i) => {
      pdf.text(h, fxPos + 2, y + 5);
      fxPos += factorColWidths[i];
    });
    y += 9;

    uvprsResult.factors.forEach((factor, idx) => {
      ensureSpace(8);
      if (idx % 2 === 0) {
        pdf.setFillColor(...BG_MUTED);
        pdf.rect(M, y - 3, contentW, 7, "F");
      }

      fxPos = M;
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(8);

      // Label
      pdf.setTextColor(...BLACK);
      pdf.text(factor.label + (factor.known ? "" : " *"), fxPos + 2, y);
      fxPos += factorColWidths[0];

      // Weight
      pdf.setTextColor(...SLATE);
      pdf.text(`${Math.round(factor.weight * 100)}%`, fxPos + 2, y);
      fxPos += factorColWidths[1];

      // Score with 3-tier color
      const fColor: [number, number, number] =
        factor.score <= 33 ? GREEN :
        factor.score <= 67 ? AMBER :
        RED;
      pdf.setTextColor(...fColor);
      pdf.setFont("helvetica", "bold");
      pdf.text(`${Math.round(factor.score)}`, fxPos + 2, y);
      fxPos += factorColWidths[2];

      // Description
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(...SLATE);
      const descLines = pdf.splitTextToSize(factor.description, factorColWidths[3] - 4);
      pdf.text(descLines[0] || "", fxPos + 2, y);
      y += 7;
    });

    if (uvprsResult.knownFactorCount < uvprsResult.factors.length) {
      y += 2;
      pdf.setFontSize(7);
      pdf.setTextColor(...SLATE);
      pdf.text("* Unknown factors use neutral score; weight redistributed to known factors.", M, y);
      y += 5;
    }
  }

  // ══════════════════════════════════════════════
  // VEHICLE HEALTH SCORE
  // ══════════════════════════════════════════════
  sectionTitle("🚗", "Vehicle Health");

  // Health score
  ensureSpace(12);
  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(...BLACK);
  pdf.text(`${historyAnalysis.healthScore}`, M + 5, y + 2);
  pdf.setFontSize(9);
  pdf.setTextColor(...SLATE);
  pdf.text("/ 100", M + 22, y + 2);

  // Progress bar
  const barY = y + 5;
  pdf.setFillColor(230, 230, 230);
  pdf.roundedRect(M, barY, contentW, 3, 1.5, 1.5, "F");
  const healthColor = historyAnalysis.healthScore >= 70 ? GREEN : historyAnalysis.healthScore >= 40 ? AMBER : RED;
  pdf.setFillColor(...healthColor);
  pdf.roundedRect(M, barY, contentW * (historyAnalysis.healthScore / 100), 3, 1.5, 1.5, "F");
  y += 14;

  // Positives
  if (historyAnalysis.positives.length > 0) {
    wrappedText("Positives:", 9, GREEN, true);
    historyAnalysis.positives.forEach((item) => {
      wrappedText(`• ${item}`, 8, SLATE, false, 3);
    });
  }

  // Concerns
  if (historyAnalysis.concerns.length > 0) {
    wrappedText("Concerns:", 9, RED, true);
    historyAnalysis.concerns.forEach((item) => {
      wrappedText(`• ${item}`, 8, SLATE, false, 3);
    });
  }

  // ══════════════════════════════════════════════
  // SERVICE HISTORY
  // ══════════════════════════════════════════════
  const hasSvcData =
    (serviceHistory?.majorServicesDone?.length ?? 0) > 0 ||
    (serviceHistory?.majorServicesDue?.length ?? 0) > 0 ||
    (serviceHistory?.chronicRepairSystems?.length ?? 0) > 0 ||
    serviceHistory?.serviceGapMiles != null;

  if (hasSvcData) {
    sectionTitle("🔧", "Service History");

    // Service gap
    if (serviceHistory?.serviceGapMiles != null) {
      const gap = serviceHistory.serviceGapMiles;
      const gapColor = gap <= 10000 ? GREEN : gap <= 20000 ? AMBER : RED;
      ensureSpace(12);
      pdf.setFillColor(...BG_MUTED);
      pdf.roundedRect(M, y, contentW, 10, 2, 2, "F");
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(...gapColor);
      pdf.text(`Largest service gap: ${gap.toLocaleString()} miles`, M + 4, y + 6);
      pdf.setFont("helvetica", "normal");
      y += 14;
    }

    // Done items
    if (serviceHistory?.majorServicesDone?.length) {
      serviceHistory.majorServicesDone.forEach((s) => {
        wrappedText(`✓ ${s}  [Completed]`, 8, GREEN, false, 3);
      });
    }
    // Due items
    if (serviceHistory?.majorServicesDue?.length) {
      serviceHistory.majorServicesDue.forEach((s) => {
        wrappedText(`⚠ ${s}  [Overdue]`, 8, AMBER, false, 3);
      });
    }
    // Chronic items
    if (serviceHistory?.chronicRepairSystems?.length) {
      serviceHistory.chronicRepairSystems.forEach((s) => {
        wrappedText(`⚠ Chronic: ${s}  [Repeat Issue]`, 8, RED, false, 3);
      });
    }
  }

  // ══════════════════════════════════════════════
  // 5-YEAR DEPRECIATION & EQUITY
  // ══════════════════════════════════════════════
  sectionTitle("📉", "5-Year Depreciation & Equity");

  // Depreciation table
  const cols = ["Year", "Private Value", "Trade-In", "Loan Balance", "Repairs", "Net Equity"];
  const colWidths = [20, 32, 30, 32, 28, 30];

  ensureSpace(depreciationTable.length * 7 + 14);
  pdf.setFillColor(...TEAL);
  pdf.rect(M, y, contentW, 7, "F");
  pdf.setTextColor(...WHITE);
  pdf.setFontSize(8);
  pdf.setFont("helvetica", "bold");
  let xPos = M;
  cols.forEach((col, i) => {
    pdf.text(col, xPos + 2, y + 5);
    xPos += colWidths[i];
  });
  y += 9;

  let cumulativeRepairs = 0;
  depreciationTable.forEach((row, index) => {
    cumulativeRepairs += row.repairCosts;
    const netEquity = row.tradeInValue - row.loanBalance - cumulativeRepairs;

    ensureSpace(8);
    if (index % 2 === 0) {
      pdf.setFillColor(...BG_MUTED);
      pdf.rect(M, y - 3, contentW, 7, "F");
    }

    xPos = M;
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);

    const rowData = [
      `Year ${row.year}`,
      fmt(row.privateValue),
      fmt(row.tradeInValue),
      fmt(row.loanBalance),
      fmt(cumulativeRepairs),
      `${netEquity >= 0 ? "+" : ""}${fmt(netEquity)}`,
    ];

    rowData.forEach((cell, i) => {
      if (i === 5) {
        pdf.setTextColor(netEquity >= 0 ? 34 : 220, netEquity >= 0 ? 197 : 38, netEquity >= 0 ? 94 : 38);
        pdf.setFont("helvetica", "bold");
      } else {
        pdf.setTextColor(...BLACK);
      }
      pdf.text(cell, xPos + 2, y);
      xPos += colWidths[i];
    });
    y += 7;
  });

  // ══════════════════════════════════════════════
  // RISK FACTORS
  // ══════════════════════════════════════════════
  sectionTitle("⚠", "Risk Factors");

  wrappedText("Depreciation Risk:", 9, BLACK, true);
  wrappedText(riskAssessment.depreciationRisk, 8, SLATE);

  if (riskAssessment.reliabilityConcerns.length > 0) {
    wrappedText("Reliability Concerns:", 9, BLACK, true);
    riskAssessment.reliabilityConcerns.forEach((concern) => {
      wrappedText(`• ${concern}`, 8, SLATE, false, 3);
    });
  }

  if (riskAssessment.valueProposition) {
    ensureSpace(14);
    pdf.setFillColor(...BG_MUTED);
    pdf.roundedRect(M, y, contentW, 12, 2, 2, "F");
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(...BLACK);
    pdf.text("Value Proposition", M + 4, y + 5);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(...SLATE);
    const vpLines = pdf.splitTextToSize(riskAssessment.valueProposition, contentW - 8);
    pdf.text(vpLines[0] || "", M + 4, y + 9);
    y += 14;
  }

  // ══════════════════════════════════════════════
  // EXPERT OPINION
  // ══════════════════════════════════════════════
  sectionTitle("📋", "Expert Opinion");
  wrappedText(riskAssessment.expertOpinion, 9, SLATE);

  // ══════════════════════════════════════════════
  // DEALER REVIEW (Pro only)
  // ══════════════════════════════════════════════
  if (dealerReview) {
    sectionTitle("🏪", "Dealership Review");

    wrappedText(dealerReview.dealerName, 11, BLACK, true);

    // Trust score box
    ensureSpace(20);
    const dsColor: [number, number, number] =
      dealerReview.trustScore >= 70 ? GREEN :
      dealerReview.trustScore >= 50 ? AMBER : RED;

    pdf.setFillColor(...BG_MUTED);
    pdf.roundedRect(M, y, 55, 16, 2, 2, "F");
    pdf.setFontSize(7);
    pdf.setTextColor(...SLATE);
    pdf.text("Trust Score", M + 4, y + 5);
    pdf.setFontSize(13);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(...dsColor);
    pdf.text(`${dealerReview.trustScore}/100`, M + 4, y + 13);

    // Sentiment badge
    const sentimentText = dealerReview.sentiment.charAt(0).toUpperCase() + dealerReview.sentiment.slice(1);
    const sentimentColor: [number, number, number] =
      dealerReview.sentiment === "positive" ? GREEN :
      dealerReview.sentiment === "mixed" ? AMBER :
      dealerReview.sentiment === "negative" ? RED : SLATE;
    pdf.setFillColor(...sentimentColor);
    pdf.roundedRect(M + 60, y + 4, 26, 8, 2, 2, "F");
    pdf.setFontSize(7);
    pdf.setTextColor(...WHITE);
    pdf.text(sentimentText, M + 63, y + 9);
    y += 20;

    wrappedText(dealerReview.summary, 8, SLATE);

    if (dealerReview.positives.length > 0) {
      wrappedText("Positives:", 9, GREEN, true);
      dealerReview.positives.forEach((item) => wrappedText(`• ${item}`, 8, SLATE, false, 3));
    }
    if (dealerReview.watchOuts.length > 0) {
      wrappedText("Watch Out:", 9, RED, true);
      dealerReview.watchOuts.forEach((item) => wrappedText(`• ${item}`, 8, SLATE, false, 3));
    }
    if (dealerReview.sources.length > 0) {
      y += 2;
      pdf.setFontSize(7);
      pdf.setTextColor(...SLATE);
      pdf.text(`Sources: ${dealerReview.sources.join(", ")}`, M, y);
      y += 5;
    }
  }

  // ══════════════════════════════════════════════
  // RECOMMENDATION CARD (matching the website bottom card)
  // ══════════════════════════════════════════════
  ensureSpace(30);
  y += 4;
  const recColor = uvprsResult
    ? (uvprsResult.riskLevel === "low" ? GREEN : uvprsResult.riskLevel === "moderate" ? AMBER : RED)
    : (riskAssessment.level === "low" ? GREEN : riskAssessment.level === "medium" ? AMBER : RED);
  const recLabel = uvprsResult
    ? uvprsResult.riskLabel.toUpperCase()
    : `${riskAssessment.level.toUpperCase()} RISK`;

  pdf.setDrawColor(...recColor);
  pdf.setLineWidth(0.8);
  pdf.roundedRect(M, y, contentW, 28, 3, 3, "S");

  // Badge
  pdf.setFillColor(...recColor);
  const badgeW = pdf.getTextWidth(recLabel) * 0.35 + 10;
  pdf.roundedRect(M + (contentW - badgeW) / 2, y + 3, badgeW, 7, 2, 2, "F");
  pdf.setFontSize(7);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(...WHITE);
  pdf.text(recLabel, M + (contentW - badgeW) / 2 + 3, y + 8);

  // Fair offer
  pdf.setFontSize(9);
  pdf.setTextColor(...SLATE);
  pdf.text("Fair Offer Price", M + contentW / 2 - 12, y + 15);
  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(...BLACK);
  const fairOfferStr = fmt(riskAssessment.fairOfferPrice);
  pdf.text(fairOfferStr, M + contentW / 2 - pdf.getTextWidth(fairOfferStr) / 2, y + 23);

  y += 32;

  // ── Footer on last page ──
  addFooter();

  // Save
  const fileName = `CarWise_Report_${vehicle.year}_${vehicle.make}_${vehicle.model}.pdf`;
  pdf.save(fileName);
}

// Alternative: Generate PDF from HTML element
export async function generatePDFFromElement(elementId: string, fileName: string): Promise<void> {
  const { default: html2canvas } = await import("html2canvas");
  const element = document.getElementById(elementId);
  if (!element) throw new Error(`Element with id "${elementId}" not found`);

  const canvas = await html2canvas(element, { scale: 2, useCORS: true, logging: false });
  const imgData = canvas.toDataURL("image/png");
  const pdf = new jsPDF("p", "mm", "a4");
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const imgWidth = pageWidth;
  const imgHeight = (canvas.height * imgWidth) / canvas.width;

  let heightLeft = imgHeight;
  let position = 0;
  pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
  heightLeft -= pageHeight;
  while (heightLeft > 0) {
    position = heightLeft - imgHeight;
    pdf.addPage();
    pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;
  }
  pdf.save(fileName);
}
