// US Sales Tax Data by State and Counties
// County rates shown are the LOCAL add-on rate (on top of state base rate).
// Sources: State revenue departments, Tax Foundation 2025, CDTFA, Texas Comptroller.
// Note: Rates change periodically — these are the best available 2025 figures for estimation.

export interface CountyTax {
  name: string;
  rate: number; // Additional county/local rate on top of state base rate
}

export interface StateTax {
  name: string;
  abbreviation: string;
  stateRate: number;
  avgLocalRate: number;
  counties?: CountyTax[];
}

export const STATE_TAX_DATA: StateTax[] = [
  {
    name: "Alabama", abbreviation: "AL", stateRate: 4.0, avgLocalRate: 5.24,
    counties: [
      { name: "Jefferson County", rate: 5.5 },
      { name: "Mobile County", rate: 5.0 },
      { name: "Madison County", rate: 5.5 },
      { name: "Montgomery County", rate: 5.5 },
      { name: "Shelby County", rate: 6.0 },
      { name: "Tuscaloosa County", rate: 5.5 },
      { name: "Lee County", rate: 5.0 },
      { name: "Calhoun County", rate: 5.0 },
      { name: "Etowah County", rate: 5.0 },
      { name: "Morgan County", rate: 5.5 },
      { name: "Baldwin County", rate: 3.0 },
      { name: "Marshall County", rate: 5.5 },
      { name: "Limestone County", rate: 5.5 },
      { name: "Talladega County", rate: 5.0 },
      { name: "Walker County", rate: 5.0 },
      { name: "Elmore County", rate: 5.5 },
      { name: "St. Clair County", rate: 5.0 },
      { name: "Houston County", rate: 5.0 },
      { name: "Blount County", rate: 5.0 },
      { name: "DeKalb County", rate: 5.0 },
    ]
  },
  { name: "Alaska", abbreviation: "AK", stateRate: 0, avgLocalRate: 1.82,
    counties: [
      { name: "Anchorage Municipality", rate: 0 },
      { name: "Fairbanks North Star Borough", rate: 0 },
      { name: "Matanuska-Susitna Borough", rate: 0 },
      { name: "Kenai Peninsula Borough", rate: 3.0 },
      { name: "Juneau City and Borough", rate: 5.0 },
      { name: "Sitka City and Borough", rate: 6.0 },
      { name: "Ketchikan Gateway Borough", rate: 2.0 },
    ]
  },
  {
    name: "Arizona", abbreviation: "AZ", stateRate: 5.6, avgLocalRate: 2.8,
    counties: [
      { name: "Maricopa County", rate: 0.7 },
      { name: "Pima County", rate: 0.5 },
      { name: "Pinal County", rate: 1.1 },
      { name: "Yavapai County", rate: 0.75 },
      { name: "Mohave County", rate: 0.75 },
      { name: "Yuma County", rate: 1.112 },
      { name: "Coconino County", rate: 1.125 },
      { name: "Navajo County", rate: 1.335 },
      { name: "Apache County", rate: 1.0 },
      { name: "Graham County", rate: 1.0 },
      { name: "Cochise County", rate: 0.5 },
      { name: "Gila County", rate: 1.0 },
      { name: "Santa Cruz County", rate: 1.2 },
      { name: "La Paz County", rate: 1.0 },
      { name: "Greenlee County", rate: 1.0 },
    ]
  },
  {
    name: "Arkansas", abbreviation: "AR", stateRate: 6.5, avgLocalRate: 2.97,
    counties: [
      { name: "Pulaski County", rate: 1.0 },
      { name: "Washington County", rate: 1.25 },
      { name: "Benton County", rate: 1.0 },
      { name: "Sebastian County", rate: 1.5 },
      { name: "Faulkner County", rate: 1.0 },
      { name: "Saline County", rate: 1.0 },
      { name: "Craighead County", rate: 1.75 },
      { name: "Garland County", rate: 1.5 },
      { name: "Jefferson County", rate: 2.0 },
      { name: "White County", rate: 1.0 },
      { name: "Lonoke County", rate: 1.0 },
      { name: "Greene County", rate: 2.5 },
      { name: "Pope County", rate: 1.5 },
      { name: "Cleburne County", rate: 2.0 },
      { name: "Miller County", rate: 2.0 },
    ]
  },
  {
    name: "California", abbreviation: "CA", stateRate: 7.25, avgLocalRate: 1.57,
    counties: [
      { name: "Los Angeles County", rate: 2.25 },
      { name: "San Diego County", rate: 0.5 },
      { name: "Orange County", rate: 0.5 },
      { name: "Riverside County", rate: 0.5 },
      { name: "San Bernardino County", rate: 0.5 },
      { name: "Santa Clara County", rate: 1.875 },
      { name: "Alameda County", rate: 3.5 },
      { name: "Sacramento County", rate: 0.5 },
      { name: "Contra Costa County", rate: 1.5 },
      { name: "Fresno County", rate: 0.725 },
      { name: "San Francisco County", rate: 1.25 },
      { name: "Kern County", rate: 0.5 },
      { name: "Ventura County", rate: 0.5 },
      { name: "San Mateo County", rate: 0.5 },
      { name: "San Joaquin County", rate: 1.0 },
      { name: "Stanislaus County", rate: 0.5 },
      { name: "Sonoma County", rate: 1.25 },
      { name: "Tulare County", rate: 0.5 },
      { name: "Solano County", rate: 1.375 },
      { name: "Monterey County", rate: 0.5 },
      { name: "Santa Barbara County", rate: 0.5 },
      { name: "Placer County", rate: 0.5 },
      { name: "San Luis Obispo County", rate: 0.5 },
      { name: "Santa Cruz County", rate: 1.5 },
      { name: "Marin County", rate: 0.5 },
      { name: "Merced County", rate: 0.5 },
      { name: "Butte County", rate: 1.0 },
      { name: "Yolo County", rate: 0.5 },
      { name: "El Dorado County", rate: 0.5 },
      { name: "Shasta County", rate: 0.5 },
      { name: "Imperial County", rate: 0.5 },
      { name: "Kings County", rate: 0.5 },
      { name: "Madera County", rate: 0.5 },
      { name: "Napa County", rate: 0.5 },
      { name: "Humboldt County", rate: 0.5 },
      { name: "Nevada County", rate: 0.5 },
      { name: "Mendocino County", rate: 0.5 },
      { name: "Sutter County", rate: 0.5 },
      { name: "Yuba County", rate: 0.5 },
      { name: "Lake County", rate: 0.5 },
      { name: "San Benito County", rate: 1.125 },
      { name: "Tuolumne County", rate: 0.5 },
      { name: "Calaveras County", rate: 1.5 },
      { name: "Amador County", rate: 0.75 },
      { name: "Tehama County", rate: 0.5 },
      { name: "Glenn County", rate: 0.5 },
      { name: "Lassen County", rate: 0.5 },
      { name: "Del Norte County", rate: 0.5 },
      { name: "Plumas County", rate: 0.5 },
      { name: "Colusa County", rate: 0.5 },
      { name: "Mariposa County", rate: 0.5 },
      { name: "Mono County", rate: 0.5 },
      { name: "Inyo County", rate: 0.5 },
      { name: "Trinity County", rate: 0.5 },
      { name: "Siskiyou County", rate: 0.5 },
      { name: "Modoc County", rate: 0.5 },
      { name: "Sierra County", rate: 0.5 },
      { name: "Alpine County", rate: 0.5 },
    ]
  },
  {
    name: "Colorado", abbreviation: "CO", stateRate: 2.9, avgLocalRate: 4.87,
    counties: [
      { name: "Denver County", rate: 5.81 },
      { name: "El Paso County", rate: 2.12 },
      { name: "Arapahoe County", rate: 2.5 },
      { name: "Jefferson County", rate: 2.0 },
      { name: "Adams County", rate: 2.0 },
      { name: "Douglas County", rate: 1.0 },
      { name: "Larimer County", rate: 2.8 },
      { name: "Weld County", rate: 0.0 },
      { name: "Boulder County", rate: 1.185 },
      { name: "Broomfield County", rate: 4.15 },
      { name: "Mesa County", rate: 2.0 },
      { name: "Garfield County", rate: 2.0 },
      { name: "Pueblo County", rate: 3.7 },
      { name: "La Plata County", rate: 2.0 },
      { name: "Fremont County", rate: 2.5 },
      { name: "Eagle County", rate: 1.5 },
      { name: "Pitkin County", rate: 3.1 },
      { name: "Summit County", rate: 2.0 },
      { name: "Delta County", rate: 2.0 },
      { name: "Montrose County", rate: 2.0 },
      { name: "Routt County", rate: 2.5 },
      { name: "Teller County", rate: 1.0 },
      { name: "Elbert County", rate: 1.0 },
      { name: "Morgan County", rate: 2.0 },
    ]
  },
  { name: "Connecticut", abbreviation: "CT", stateRate: 6.35, avgLocalRate: 0 },
  { name: "Delaware", abbreviation: "DE", stateRate: 0, avgLocalRate: 0 },
  {
    name: "Florida", abbreviation: "FL", stateRate: 6.0, avgLocalRate: 1.02,
    counties: [
      { name: "Miami-Dade County", rate: 1.0 },
      { name: "Broward County", rate: 1.0 },
      { name: "Palm Beach County", rate: 1.0 },
      { name: "Hillsborough County", rate: 1.5 },
      { name: "Orange County", rate: 0.5 },
      { name: "Pinellas County", rate: 1.0 },
      { name: "Duval County", rate: 0.5 },
      { name: "Lee County", rate: 0.5 },
      { name: "Polk County", rate: 1.0 },
      { name: "Brevard County", rate: 1.0 },
      { name: "Volusia County", rate: 0.5 },
      { name: "Pasco County", rate: 1.0 },
      { name: "Sarasota County", rate: 1.0 },
      { name: "Collier County", rate: 1.0 },
      { name: "Seminole County", rate: 1.0 },
      { name: "Manatee County", rate: 1.5 },
      { name: "Marion County", rate: 0.5 },
      { name: "Alachua County", rate: 1.5 },
      { name: "Escambia County", rate: 1.5 },
      { name: "Lake County", rate: 1.0 },
      { name: "St. Johns County", rate: 0.5 },
      { name: "St. Lucie County", rate: 1.0 },
      { name: "Leon County", rate: 1.5 },
      { name: "Osceola County", rate: 1.5 },
      { name: "Indian River County", rate: 0.5 },
      { name: "Clay County", rate: 1.0 },
      { name: "Santa Rosa County", rate: 1.0 },
      { name: "Okaloosa County", rate: 0.5 },
      { name: "Flagler County", rate: 1.0 },
      { name: "Charlotte County", rate: 0.5 },
      { name: "Hernando County", rate: 1.5 },
      { name: "Martin County", rate: 0.0 },
      { name: "Citrus County", rate: 1.0 },
      { name: "Putnam County", rate: 1.0 },
      { name: "Nassau County", rate: 0.5 },
      { name: "Highlands County", rate: 1.0 },
      { name: "Sumter County", rate: 1.0 },
      { name: "Monroe County", rate: 1.5 },
      { name: "Bay County", rate: 1.5 },
      { name: "Columbia County", rate: 1.0 },
    ]
  },
  {
    name: "Georgia", abbreviation: "GA", stateRate: 4.0, avgLocalRate: 3.32,
    counties: [
      { name: "Fulton County", rate: 3.0 },
      { name: "Gwinnett County", rate: 3.0 },
      { name: "Cobb County", rate: 2.0 },
      { name: "DeKalb County", rate: 3.0 },
      { name: "Cherokee County", rate: 3.0 },
      { name: "Clayton County", rate: 3.0 },
      { name: "Hall County", rate: 3.0 },
      { name: "Henry County", rate: 3.0 },
      { name: "Forsyth County", rate: 3.0 },
      { name: "Richmond County", rate: 3.0 },
      { name: "Columbia County", rate: 3.0 },
      { name: "Houston County", rate: 3.0 },
      { name: "Carroll County", rate: 3.0 },
      { name: "Muscogee County", rate: 3.0 },
      { name: "Douglas County", rate: 3.0 },
      { name: "Chatham County", rate: 3.0 },
      { name: "Paulding County", rate: 3.0 },
      { name: "Bibb County", rate: 3.0 },
      { name: "Newton County", rate: 3.0 },
      { name: "Lowndes County", rate: 3.0 },
      { name: "Coweta County", rate: 3.0 },
      { name: "Clarke County", rate: 4.0 },
      { name: "Rockdale County", rate: 3.0 },
      { name: "Bartow County", rate: 3.0 },
      { name: "Whitfield County", rate: 3.0 },
    ]
  },
  {
    name: "Hawaii", abbreviation: "HI", stateRate: 4.0, avgLocalRate: 0.44,
    counties: [
      { name: "Honolulu County", rate: 0.5 },
      { name: "Hawaii County", rate: 0.25 },
      { name: "Maui County", rate: 0.5 },
      { name: "Kauai County", rate: 0.5 },
    ]
  },
  { name: "Idaho", abbreviation: "ID", stateRate: 6.0, avgLocalRate: 0.03,
    counties: [
      { name: "Ada County", rate: 0.0 },
      { name: "Canyon County", rate: 0.0 },
      { name: "Kootenai County", rate: 0.0 },
      { name: "Bonneville County", rate: 0.0 },
      { name: "Twin Falls County", rate: 0.0 },
      { name: "Bannock County", rate: 0.0 },
      { name: "Nez Perce County", rate: 0.0 },
    ]
  },
  {
    name: "Illinois", abbreviation: "IL", stateRate: 6.25, avgLocalRate: 2.59,
    counties: [
      { name: "Cook County", rate: 1.75 },
      { name: "DuPage County", rate: 0.75 },
      { name: "Lake County", rate: 0.25 },
      { name: "Will County", rate: 1.75 },
      { name: "Kane County", rate: 0.75 },
      { name: "McHenry County", rate: 0.75 },
      { name: "Winnebago County", rate: 1.25 },
      { name: "St. Clair County", rate: 1.25 },
      { name: "Sangamon County", rate: 0.75 },
      { name: "Macon County", rate: 0.75 },
      { name: "Champaign County", rate: 0.75 },
      { name: "Peoria County", rate: 0.75 },
      { name: "Rock Island County", rate: 1.0 },
      { name: "Kendall County", rate: 0.75 },
      { name: "Tazewell County", rate: 0.75 },
      { name: "Kankakee County", rate: 0.75 },
      { name: "Madison County", rate: 0.75 },
      { name: "McLean County", rate: 0.75 },
      { name: "Whiteside County", rate: 0.75 },
      { name: "Boone County", rate: 0.75 },
      { name: "De Kalb County", rate: 0.75 },
      { name: "Vermilion County", rate: 0.75 },
      { name: "LaSalle County", rate: 0.75 },
      { name: "Grundy County", rate: 0.75 },
    ]
  },
  { name: "Indiana", abbreviation: "IN", stateRate: 7.0, avgLocalRate: 0 },
  {
    name: "Iowa", abbreviation: "IA", stateRate: 6.0, avgLocalRate: 0.94,
    counties: [
      { name: "Polk County", rate: 1.0 },
      { name: "Linn County", rate: 1.0 },
      { name: "Scott County", rate: 1.0 },
      { name: "Johnson County", rate: 1.0 },
      { name: "Black Hawk County", rate: 1.0 },
      { name: "Story County", rate: 1.0 },
      { name: "Woodbury County", rate: 1.0 },
      { name: "Dubuque County", rate: 1.0 },
      { name: "Pottawattamie County", rate: 1.0 },
      { name: "Dallas County", rate: 1.0 },
      { name: "Marshall County", rate: 1.0 },
      { name: "Warren County", rate: 1.0 },
      { name: "Clinton County", rate: 1.0 },
      { name: "Cerro Gordo County", rate: 1.0 },
      { name: "Webster County", rate: 1.0 },
    ]
  },
  {
    name: "Kansas", abbreviation: "KS", stateRate: 6.5, avgLocalRate: 2.19,
    counties: [
      { name: "Johnson County", rate: 1.475 },
      { name: "Sedgwick County", rate: 1.0 },
      { name: "Shawnee County", rate: 1.15 },
      { name: "Douglas County", rate: 1.3 },
      { name: "Wyandotte County", rate: 1.5 },
      { name: "Leavenworth County", rate: 1.5 },
      { name: "Riley County", rate: 1.0 },
      { name: "Saline County", rate: 1.5 },
      { name: "Butler County", rate: 1.0 },
      { name: "Reno County", rate: 1.5 },
      { name: "Ellis County", rate: 1.0 },
      { name: "Crawford County", rate: 1.0 },
      { name: "Harvey County", rate: 1.0 },
      { name: "Finney County", rate: 1.0 },
    ]
  },
  { name: "Kentucky", abbreviation: "KY", stateRate: 6.0, avgLocalRate: 0 },
  {
    name: "Louisiana", abbreviation: "LA", stateRate: 4.45, avgLocalRate: 5.10,
    counties: [
      { name: "Jefferson Parish", rate: 4.75 },
      { name: "Orleans Parish", rate: 5.0 },
      { name: "East Baton Rouge Parish", rate: 5.0 },
      { name: "Caddo Parish", rate: 4.6 },
      { name: "Calcasieu Parish", rate: 4.45 },
      { name: "St. Tammany Parish", rate: 3.7 },
      { name: "Lafayette Parish", rate: 4.0 },
      { name: "Ouachita Parish", rate: 4.95 },
      { name: "Livingston Parish", rate: 5.5 },
      { name: "Bossier Parish", rate: 4.5 },
      { name: "St. Landry Parish", rate: 5.5 },
      { name: "Terrebonne Parish", rate: 4.5 },
      { name: "Lafourche Parish", rate: 4.55 },
      { name: "Ascension Parish", rate: 4.0 },
      { name: "Rapides Parish", rate: 4.6 },
    ]
  },
  { name: "Maine", abbreviation: "ME", stateRate: 5.5, avgLocalRate: 0 },
  { name: "Maryland", abbreviation: "MD", stateRate: 6.0, avgLocalRate: 0 },
  { name: "Massachusetts", abbreviation: "MA", stateRate: 6.25, avgLocalRate: 0 },
  { name: "Michigan", abbreviation: "MI", stateRate: 6.0, avgLocalRate: 0 },
  {
    name: "Minnesota", abbreviation: "MN", stateRate: 6.875, avgLocalRate: 0.61,
    counties: [
      { name: "Hennepin County", rate: 0.15 },
      { name: "Ramsey County", rate: 0.15 },
      { name: "Dakota County", rate: 0.25 },
      { name: "Anoka County", rate: 0.25 },
      { name: "Washington County", rate: 0.25 },
      { name: "Scott County", rate: 0.25 },
      { name: "Carver County", rate: 0.5 },
      { name: "Olmsted County", rate: 0.5 },
      { name: "St. Louis County", rate: 0.5 },
      { name: "Stearns County", rate: 0.5 },
      { name: "Wright County", rate: 0.5 },
      { name: "Sherburne County", rate: 0.5 },
      { name: "Rice County", rate: 0.5 },
      { name: "Blue Earth County", rate: 0.5 },
      { name: "Clay County", rate: 0.5 },
    ]
  },
  {
    name: "Mississippi", abbreviation: "MS", stateRate: 7.0, avgLocalRate: 0.07,
    counties: [
      { name: "Hinds County", rate: 1.0 },
      { name: "Harrison County", rate: 0.25 },
      { name: "DeSoto County", rate: 0.0 },
      { name: "Jackson County", rate: 0.0 },
      { name: "Rankin County", rate: 0.0 },
      { name: "Madison County", rate: 0.0 },
      { name: "Forrest County", rate: 0.25 },
      { name: "Lauderdale County", rate: 0.0 },
      { name: "Lee County", rate: 0.0 },
      { name: "Lowndes County", rate: 0.0 },
    ]
  },
  {
    name: "Missouri", abbreviation: "MO", stateRate: 4.225, avgLocalRate: 4.06,
    counties: [
      { name: "St. Louis County", rate: 2.638 },
      { name: "Jackson County", rate: 2.25 },
      { name: "St. Louis City", rate: 4.454 },
      { name: "Greene County", rate: 2.125 },
      { name: "Clay County", rate: 2.125 },
      { name: "Boone County", rate: 2.0 },
      { name: "Jefferson County", rate: 1.625 },
      { name: "Cass County", rate: 1.625 },
      { name: "Christian County", rate: 2.125 },
      { name: "St. Charles County", rate: 1.5 },
      { name: "Jasper County", rate: 2.125 },
      { name: "Buchanan County", rate: 2.0 },
      { name: "Cole County", rate: 2.0 },
      { name: "Platte County", rate: 2.0 },
      { name: "Franklin County", rate: 2.0 },
    ]
  },
  { name: "Montana", abbreviation: "MT", stateRate: 0, avgLocalRate: 0 },
  {
    name: "Nebraska", abbreviation: "NE", stateRate: 5.5, avgLocalRate: 1.44,
    counties: [
      { name: "Douglas County", rate: 1.5 },
      { name: "Lancaster County", rate: 1.75 },
      { name: "Sarpy County", rate: 1.5 },
      { name: "Hall County", rate: 2.0 },
      { name: "Buffalo County", rate: 2.0 },
      { name: "Dodge County", rate: 1.5 },
      { name: "Adams County", rate: 1.5 },
      { name: "Madison County", rate: 1.5 },
      { name: "Lincoln County", rate: 2.0 },
      { name: "Scotts Bluff County", rate: 2.0 },
    ]
  },
  {
    name: "Nevada", abbreviation: "NV", stateRate: 6.85, avgLocalRate: 1.38,
    counties: [
      { name: "Clark County", rate: 1.525 },
      { name: "Washoe County", rate: 1.415 },
      { name: "Carson City", rate: 1.0 },
      { name: "Elko County", rate: 0.75 },
      { name: "Douglas County", rate: 0.25 },
      { name: "Lyon County", rate: 1.25 },
      { name: "Churchill County", rate: 0.25 },
      { name: "Nye County", rate: 0.25 },
      { name: "Humboldt County", rate: 0.25 },
      { name: "Lander County", rate: 0.25 },
      { name: "White Pine County", rate: 0.25 },
      { name: "Pershing County", rate: 0.25 },
      { name: "Mineral County", rate: 0.25 },
      { name: "Storey County", rate: 0.25 },
      { name: "Esmeralda County", rate: 0.25 },
      { name: "Eureka County", rate: 0.25 },
    ]
  },
  { name: "New Hampshire", abbreviation: "NH", stateRate: 0, avgLocalRate: 0 },
  { name: "New Jersey", abbreviation: "NJ", stateRate: 6.625, avgLocalRate: 0 },
  {
    name: "New Mexico", abbreviation: "NM", stateRate: 4.875, avgLocalRate: 2.71,
    counties: [
      { name: "Bernalillo County", rate: 2.8125 },
      { name: "Dona Ana County", rate: 2.125 },
      { name: "Sandoval County", rate: 2.125 },
      { name: "Santa Fe County", rate: 2.4375 },
      { name: "San Juan County", rate: 2.3125 },
      { name: "Chaves County", rate: 2.25 },
      { name: "Eddy County", rate: 2.25 },
      { name: "McKinley County", rate: 3.3125 },
      { name: "Lea County", rate: 2.3125 },
      { name: "Otero County", rate: 2.5625 },
      { name: "Valencia County", rate: 2.125 },
      { name: "Rio Arriba County", rate: 3.0625 },
      { name: "Taos County", rate: 2.6875 },
    ]
  },
  {
    name: "New York", abbreviation: "NY", stateRate: 4.0, avgLocalRate: 4.52,
    counties: [
      { name: "New York City", rate: 4.5 },
      { name: "Nassau County", rate: 4.625 },
      { name: "Suffolk County", rate: 4.25 },
      { name: "Westchester County", rate: 4.375 },
      { name: "Erie County", rate: 4.75 },
      { name: "Monroe County", rate: 4.5 },
      { name: "Onondaga County", rate: 4.5 },
      { name: "Albany County", rate: 4.0 },
      { name: "Dutchess County", rate: 3.75 },
      { name: "Orange County", rate: 3.75 },
      { name: "Rockland County", rate: 4.375 },
      { name: "Saratoga County", rate: 3.0 },
      { name: "Ulster County", rate: 4.0 },
      { name: "Broome County", rate: 4.5 },
      { name: "Niagara County", rate: 4.75 },
      { name: "Rensselaer County", rate: 4.0 },
      { name: "Schenectady County", rate: 4.0 },
      { name: "Oneida County", rate: 4.75 },
      { name: "Chemung County", rate: 4.0 },
      { name: "Chautauqua County", rate: 4.5 },
      { name: "Tompkins County", rate: 4.0 },
      { name: "Jefferson County", rate: 4.0 },
      { name: "Steuben County", rate: 4.0 },
      { name: "Clinton County", rate: 4.0 },
      { name: "Columbia County", rate: 4.0 },
      { name: "Cayuga County", rate: 4.5 },
      { name: "Oswego County", rate: 4.5 },
      { name: "St. Lawrence County", rate: 4.0 },
      { name: "Livingston County", rate: 4.0 },
      { name: "Putnam County", rate: 3.75 },
      { name: "Madison County", rate: 4.0 },
      { name: "Herkimer County", rate: 4.25 },
      { name: "Warren County", rate: 4.0 },
      { name: "Washington County", rate: 4.0 },
      { name: "Sullivan County", rate: 4.5 },
      { name: "Chenango County", rate: 4.0 },
      { name: "Franklin County", rate: 4.0 },
      { name: "Otsego County", rate: 4.0 },
      { name: "Greene County", rate: 4.0 },
      { name: "Fulton County", rate: 4.0 },
      { name: "Delaware County", rate: 4.0 },
      { name: "Schoharie County", rate: 4.0 },
      { name: "Yates County", rate: 4.0 },
      { name: "Wyoming County", rate: 4.0 },
      { name: "Allegany County", rate: 4.5 },
      { name: "Schuyler County", rate: 4.0 },
      { name: "Montgomery County", rate: 4.0 },
      { name: "Tioga County", rate: 4.0 },
      { name: "Essex County", rate: 4.0 },
      { name: "Orleans County", rate: 4.0 },
      { name: "Cortland County", rate: 4.0 },
      { name: "Genesee County", rate: 4.0 },
      { name: "Wayne County", rate: 4.0 },
      { name: "Seneca County", rate: 4.0 },
      { name: "Ontario County", rate: 4.0 },
      { name: "Lewis County", rate: 4.0 },
      { name: "Hamilton County", rate: 4.0 },
    ]
  },
  {
    name: "North Carolina", abbreviation: "NC", stateRate: 4.75, avgLocalRate: 2.23,
    counties: [
      { name: "Mecklenburg County", rate: 2.75 },
      { name: "Wake County", rate: 2.5 },
      { name: "Guilford County", rate: 2.25 },
      { name: "Forsyth County", rate: 2.25 },
      { name: "Cumberland County", rate: 2.75 },
      { name: "Durham County", rate: 2.75 },
      { name: "Buncombe County", rate: 2.5 },
      { name: "Union County", rate: 2.0 },
      { name: "Cabarrus County", rate: 2.5 },
      { name: "New Hanover County", rate: 2.25 },
      { name: "Iredell County", rate: 2.25 },
      { name: "Gaston County", rate: 2.5 },
      { name: "Johnston County", rate: 2.0 },
      { name: "Catawba County", rate: 2.5 },
      { name: "Pitt County", rate: 2.0 },
      { name: "Randolph County", rate: 2.0 },
      { name: "Rowan County", rate: 2.25 },
      { name: "Davidson County", rate: 2.25 },
      { name: "Alamance County", rate: 2.0 },
      { name: "Robeson County", rate: 2.5 },
      { name: "Chatham County", rate: 2.0 },
      { name: "Harnett County", rate: 2.0 },
      { name: "Brunswick County", rate: 2.0 },
      { name: "Lincoln County", rate: 2.0 },
      { name: "Onslow County", rate: 2.0 },
      { name: "Moore County", rate: 2.5 },
      { name: "Stanly County", rate: 2.5 },
      { name: "Orange County", rate: 2.75 },
      { name: "Wayne County", rate: 2.0 },
      { name: "Surry County", rate: 2.0 },
      { name: "Wilkes County", rate: 2.25 },
    ]
  },
  {
    name: "North Dakota", abbreviation: "ND", stateRate: 5.0, avgLocalRate: 1.97,
    counties: [
      { name: "Cass County", rate: 0.5 },
      { name: "Burleigh County", rate: 0.5 },
      { name: "Grand Forks County", rate: 2.0 },
      { name: "Ward County", rate: 1.0 },
      { name: "Morton County", rate: 0.5 },
      { name: "Stark County", rate: 0.5 },
      { name: "Williams County", rate: 0.5 },
      { name: "Stutsman County", rate: 0.5 },
      { name: "Ramsey County", rate: 0.5 },
    ]
  },
  {
    name: "Ohio", abbreviation: "OH", stateRate: 5.75, avgLocalRate: 1.48,
    counties: [
      { name: "Cuyahoga County", rate: 2.25 },
      { name: "Franklin County", rate: 1.75 },
      { name: "Hamilton County", rate: 2.05 },
      { name: "Summit County", rate: 1.0 },
      { name: "Montgomery County", rate: 1.5 },
      { name: "Lucas County", rate: 2.0 },
      { name: "Butler County", rate: 0.75 },
      { name: "Stark County", rate: 1.5 },
      { name: "Lorain County", rate: 1.5 },
      { name: "Lake County", rate: 1.5 },
      { name: "Mahoning County", rate: 1.0 },
      { name: "Warren County", rate: 1.0 },
      { name: "Greene County", rate: 1.0 },
      { name: "Medina County", rate: 1.5 },
      { name: "Clermont County", rate: 1.0 },
      { name: "Delaware County", rate: 1.5 },
      { name: "Clark County", rate: 1.5 },
      { name: "Licking County", rate: 1.5 },
      { name: "Fairfield County", rate: 1.5 },
      { name: "Allen County", rate: 1.1 },
      { name: "Wayne County", rate: 1.5 },
      { name: "Trumbull County", rate: 1.0 },
      { name: "Erie County", rate: 1.25 },
      { name: "Wood County", rate: 1.0 },
      { name: "Richland County", rate: 1.5 },
      { name: "Portage County", rate: 1.5 },
      { name: "Ross County", rate: 1.5 },
      { name: "Ashtabula County", rate: 1.5 },
      { name: "Geauga County", rate: 1.0 },
      { name: "Muskingum County", rate: 1.5 },
      { name: "Tuscarawas County", rate: 1.5 },
      { name: "Columbiana County", rate: 1.5 },
      { name: "Sandusky County", rate: 1.5 },
      { name: "Hancock County", rate: 1.0 },
      { name: "Knox County", rate: 1.5 },
      { name: "Pickaway County", rate: 1.5 },
      { name: "Athens County", rate: 1.5 },
      { name: "Hocking County", rate: 1.5 },
      { name: "Hardin County", rate: 1.5 },
      { name: "Union County", rate: 1.5 },
      { name: "Morrow County", rate: 1.5 },
      { name: "Holmes County", rate: 1.5 },
      { name: "Carroll County", rate: 1.5 },
      { name: "Putnam County", rate: 1.25 },
      { name: "Paulding County", rate: 1.5 },
      { name: "Henry County", rate: 1.5 },
      { name: "Defiance County", rate: 1.0 },
      { name: "Williams County", rate: 1.5 },
      { name: "Fulton County", rate: 1.5 },
      { name: "Ottawa County", rate: 1.25 },
      { name: "Van Wert County", rate: 1.5 },
      { name: "Auglaize County", rate: 1.5 },
      { name: "Shelby County", rate: 1.5 },
      { name: "Logan County", rate: 1.5 },
      { name: "Champaign County", rate: 1.5 },
      { name: "Mercer County", rate: 1.5 },
      { name: "Darke County", rate: 1.5 },
      { name: "Preble County", rate: 1.5 },
      { name: "Miami County", rate: 1.5 },
      { name: "Clinton County", rate: 1.5 },
      { name: "Fayette County", rate: 1.5 },
      { name: "Madison County", rate: 1.5 },
      { name: "Highland County", rate: 1.5 },
      { name: "Brown County", rate: 1.25 },
      { name: "Adams County", rate: 1.5 },
      { name: "Scioto County", rate: 1.5 },
      { name: "Pike County", rate: 1.5 },
      { name: "Jackson County", rate: 1.5 },
      { name: "Vinton County", rate: 1.5 },
      { name: "Gallia County", rate: 1.5 },
      { name: "Lawrence County", rate: 1.5 },
      { name: "Meigs County", rate: 1.5 },
      { name: "Washington County", rate: 1.5 },
      { name: "Morgan County", rate: 1.5 },
      { name: "Perry County", rate: 1.5 },
      { name: "Licking County", rate: 1.5 },
      { name: "Coshocton County", rate: 1.5 },
      { name: "Guernsey County", rate: 1.5 },
      { name: "Noble County", rate: 1.5 },
      { name: "Monroe County", rate: 1.5 },
      { name: "Belmont County", rate: 1.5 },
      { name: "Harrison County", rate: 1.5 },
      { name: "Jefferson County", rate: 1.5 },
      { name: "Wyandot County", rate: 1.5 },
      { name: "Crawford County", rate: 1.5 },
      { name: "Seneca County", rate: 1.5 },
      { name: "Marion County", rate: 1.5 },
      { name: "Wyandot County", rate: 1.5 },
    ]
  },
  {
    name: "Oklahoma", abbreviation: "OK", stateRate: 4.5, avgLocalRate: 4.47,
    counties: [
      { name: "Oklahoma County", rate: 4.125 },
      { name: "Tulsa County", rate: 4.017 },
      { name: "Cleveland County", rate: 3.625 },
      { name: "Canadian County", rate: 3.5 },
      { name: "Comanche County", rate: 3.625 },
      { name: "Rogers County", rate: 3.917 },
      { name: "Wagoner County", rate: 3.167 },
      { name: "Payne County", rate: 3.375 },
      { name: "Pottawatomie County", rate: 4.042 },
      { name: "Muskogee County", rate: 4.0 },
      { name: "Creek County", rate: 3.375 },
      { name: "Garfield County", rate: 3.0 },
      { name: "Washington County", rate: 3.0 },
      { name: "Pittsburg County", rate: 3.875 },
      { name: "Pontotoc County", rate: 4.75 },
    ]
  },
  { name: "Oregon", abbreviation: "OR", stateRate: 0, avgLocalRate: 0 },
  {
    name: "Pennsylvania", abbreviation: "PA", stateRate: 6.0, avgLocalRate: 0.34,
    counties: [
      { name: "Philadelphia County", rate: 2.0 },
      { name: "Allegheny County", rate: 1.0 },
      { name: "Montgomery County", rate: 0.0 },
      { name: "Bucks County", rate: 0.0 },
      { name: "Delaware County", rate: 0.0 },
      { name: "Chester County", rate: 0.0 },
      { name: "Lancaster County", rate: 0.0 },
      { name: "York County", rate: 0.0 },
      { name: "Berks County", rate: 0.0 },
      { name: "Luzerne County", rate: 0.0 },
      { name: "Lehigh County", rate: 0.0 },
      { name: "Westmoreland County", rate: 0.0 },
      { name: "Dauphin County", rate: 0.0 },
      { name: "Cumberland County", rate: 0.0 },
      { name: "Northampton County", rate: 0.0 },
      { name: "Erie County", rate: 0.0 },
      { name: "Lackawanna County", rate: 0.0 },
      { name: "Schuylkill County", rate: 0.0 },
      { name: "Cambria County", rate: 0.0 },
      { name: "Monroe County", rate: 0.0 },
      { name: "Butler County", rate: 0.0 },
      { name: "Centre County", rate: 0.0 },
      { name: "Washington County", rate: 0.0 },
      { name: "Fayette County", rate: 0.0 },
      { name: "Blair County", rate: 0.0 },
    ]
  },
  { name: "Rhode Island", abbreviation: "RI", stateRate: 7.0, avgLocalRate: 0 },
  {
    name: "South Carolina", abbreviation: "SC", stateRate: 6.0, avgLocalRate: 1.44,
    counties: [
      { name: "Greenville County", rate: 1.0 },
      { name: "Richland County", rate: 1.0 },
      { name: "Charleston County", rate: 1.0 },
      { name: "Horry County", rate: 1.5 },
      { name: "Spartanburg County", rate: 1.0 },
      { name: "Lexington County", rate: 1.0 },
      { name: "Pickens County", rate: 1.0 },
      { name: "Anderson County", rate: 1.0 },
      { name: "York County", rate: 1.5 },
      { name: "Aiken County", rate: 1.0 },
      { name: "Beaufort County", rate: 1.0 },
      { name: "Dorchester County", rate: 1.0 },
      { name: "Berkeley County", rate: 1.0 },
      { name: "Sumter County", rate: 1.0 },
      { name: "Florence County", rate: 1.0 },
      { name: "Chesterfield County", rate: 1.0 },
      { name: "Georgetown County", rate: 1.0 },
      { name: "Orangeburg County", rate: 1.0 },
      { name: "Cherokee County", rate: 1.0 },
      { name: "Lancaster County", rate: 1.5 },
    ]
  },
  {
    name: "South Dakota", abbreviation: "SD", stateRate: 4.2, avgLocalRate: 1.91,
    counties: [
      { name: "Minnehaha County", rate: 2.0 },
      { name: "Pennington County", rate: 1.5 },
      { name: "Lincoln County", rate: 2.0 },
      { name: "Brown County", rate: 1.0 },
      { name: "Brookings County", rate: 1.0 },
      { name: "Codington County", rate: 1.0 },
      { name: "Meade County", rate: 1.0 },
      { name: "Lawrence County", rate: 1.5 },
      { name: "Yankton County", rate: 2.0 },
    ]
  },
  {
    name: "Tennessee", abbreviation: "TN", stateRate: 7.0, avgLocalRate: 2.55,
    counties: [
      { name: "Shelby County", rate: 2.25 },
      { name: "Davidson County", rate: 2.25 },
      { name: "Knox County", rate: 2.25 },
      { name: "Hamilton County", rate: 2.25 },
      { name: "Williamson County", rate: 2.25 },
      { name: "Rutherford County", rate: 2.75 },
      { name: "Sullivan County", rate: 2.25 },
      { name: "Sumner County", rate: 2.25 },
      { name: "Washington County", rate: 2.25 },
      { name: "Wilson County", rate: 2.75 },
      { name: "Montgomery County", rate: 2.25 },
      { name: "Blount County", rate: 2.75 },
      { name: "Maury County", rate: 2.25 },
      { name: "Madison County", rate: 2.75 },
      { name: "Bradley County", rate: 2.75 },
      { name: "Sevier County", rate: 2.75 },
      { name: "Anderson County", rate: 2.25 },
      { name: "Putnam County", rate: 2.25 },
      { name: "Tipton County", rate: 2.75 },
      { name: "Dickson County", rate: 2.75 },
      { name: "Carter County", rate: 2.25 },
      { name: "Robertson County", rate: 2.75 },
      { name: "Jefferson County", rate: 2.75 },
      { name: "Cheatham County", rate: 2.75 },
      { name: "Gibson County", rate: 2.75 },
      { name: "Hawkins County", rate: 2.75 },
    ]
  },
  {
    name: "Texas", abbreviation: "TX", stateRate: 6.25, avgLocalRate: 1.94,
    counties: [
      { name: "Harris County", rate: 2.0 },
      { name: "Dallas County", rate: 2.0 },
      { name: "Tarrant County", rate: 2.0 },
      { name: "Bexar County", rate: 2.0 },
      { name: "Travis County", rate: 2.0 },
      { name: "Collin County", rate: 2.0 },
      { name: "Hidalgo County", rate: 2.0 },
      { name: "El Paso County", rate: 2.0 },
      { name: "Denton County", rate: 2.0 },
      { name: "Fort Bend County", rate: 2.0 },
      { name: "Montgomery County", rate: 2.0 },
      { name: "Williamson County", rate: 2.0 },
      { name: "Cameron County", rate: 2.0 },
      { name: "Nueces County", rate: 2.0 },
      { name: "Lubbock County", rate: 2.0 },
      { name: "Webb County", rate: 2.0 },
      { name: "Jefferson County", rate: 2.0 },
      { name: "Bell County", rate: 2.0 },
      { name: "Galveston County", rate: 2.0 },
      { name: "McLennan County", rate: 2.0 },
      { name: "Potter County", rate: 2.0 },
      { name: "Brazoria County", rate: 2.0 },
      { name: "Smith County", rate: 2.0 },
      { name: "Hays County", rate: 2.0 },
      { name: "Ector County", rate: 2.0 },
      { name: "Midland County", rate: 2.0 },
      { name: "Taylor County", rate: 2.0 },
      { name: "Brazos County", rate: 2.0 },
      { name: "Ellis County", rate: 2.0 },
      { name: "Johnson County", rate: 2.0 },
      { name: "Comal County", rate: 2.0 },
      { name: "Parker County", rate: 2.0 },
      { name: "Wichita County", rate: 2.0 },
      { name: "Randall County", rate: 2.0 },
      { name: "Gregg County", rate: 2.0 },
      { name: "Hunt County", rate: 2.0 },
      { name: "Tom Green County", rate: 2.0 },
      { name: "Guadalupe County", rate: 2.0 },
      { name: "Kaufman County", rate: 2.0 },
      { name: "Rockwall County", rate: 2.0 },
    ]
  },
  {
    name: "Utah", abbreviation: "UT", stateRate: 4.85, avgLocalRate: 1.99,
    counties: [
      { name: "Salt Lake County", rate: 2.35 },
      { name: "Utah County", rate: 1.85 },
      { name: "Davis County", rate: 1.35 },
      { name: "Weber County", rate: 1.85 },
      { name: "Washington County", rate: 1.6 },
      { name: "Cache County", rate: 1.1 },
      { name: "Iron County", rate: 1.6 },
      { name: "Box Elder County", rate: 1.35 },
      { name: "Tooele County", rate: 1.85 },
      { name: "Uintah County", rate: 1.6 },
      { name: "Sanpete County", rate: 1.1 },
      { name: "Carbon County", rate: 1.35 },
      { name: "Sevier County", rate: 1.1 },
      { name: "Duchesne County", rate: 1.6 },
      { name: "Summit County", rate: 1.35 },
      { name: "Morgan County", rate: 1.35 },
      { name: "Wasatch County", rate: 1.6 },
      { name: "Juab County", rate: 1.6 },
      { name: "Millard County", rate: 1.1 },
      { name: "Beaver County", rate: 1.1 },
      { name: "Kane County", rate: 1.1 },
      { name: "Garfield County", rate: 1.1 },
      { name: "Grand County", rate: 1.35 },
      { name: "San Juan County", rate: 1.6 },
      { name: "Emery County", rate: 1.1 },
      { name: "Wayne County", rate: 1.1 },
      { name: "Rich County", rate: 1.1 },
      { name: "Piute County", rate: 1.1 },
      { name: "Daggett County", rate: 1.1 },
    ]
  },
  { name: "Vermont", abbreviation: "VT", stateRate: 6.0, avgLocalRate: 0.24,
    counties: [
      { name: "Chittenden County", rate: 0.0 },
      { name: "Rutland County", rate: 0.0 },
      { name: "Washington County", rate: 0.0 },
      { name: "Windsor County", rate: 0.0 },
      { name: "Franklin County", rate: 0.0 },
      { name: "Windham County", rate: 0.0 },
      { name: "Caledonia County", rate: 0.0 },
    ]
  },
  {
    name: "Virginia", abbreviation: "VA", stateRate: 4.3, avgLocalRate: 1.0,
    counties: [
      { name: "Fairfax County", rate: 1.0 },
      { name: "Prince William County", rate: 1.0 },
      { name: "Loudoun County", rate: 1.0 },
      { name: "Chesterfield County", rate: 1.0 },
      { name: "Henrico County", rate: 1.0 },
      { name: "Virginia Beach City", rate: 1.0 },
      { name: "Arlington County", rate: 1.0 },
      { name: "Montgomery County", rate: 1.0 },
      { name: "Chesapeake City", rate: 1.0 },
      { name: "Norfolk City", rate: 1.0 },
      { name: "Roanoke County", rate: 1.0 },
      { name: "Alexandria City", rate: 1.0 },
      { name: "Stafford County", rate: 1.0 },
      { name: "Albemarle County", rate: 1.0 },
      { name: "Richmond City", rate: 1.0 },
      { name: "Hampton City", rate: 1.0 },
      { name: "Newport News City", rate: 1.0 },
      { name: "Spotsylvania County", rate: 1.0 },
      { name: "Frederick County", rate: 1.0 },
      { name: "Hanover County", rate: 1.0 },
    ]
  },
  {
    name: "Washington", abbreviation: "WA", stateRate: 6.5, avgLocalRate: 2.73,
    counties: [
      { name: "King County", rate: 3.6 },
      { name: "Pierce County", rate: 2.7 },
      { name: "Snohomish County", rate: 3.1 },
      { name: "Spokane County", rate: 2.4 },
      { name: "Clark County", rate: 1.9 },
      { name: "Thurston County", rate: 2.4 },
      { name: "Kitsap County", rate: 2.7 },
      { name: "Whatcom County", rate: 2.1 },
      { name: "Benton County", rate: 1.8 },
      { name: "Yakima County", rate: 2.0 },
      { name: "Skagit County", rate: 2.3 },
      { name: "Cowlitz County", rate: 2.3 },
      { name: "Grant County", rate: 1.8 },
      { name: "Franklin County", rate: 1.8 },
      { name: "Okanogan County", rate: 1.6 },
      { name: "Grays Harbor County", rate: 2.3 },
      { name: "Lewis County", rate: 1.8 },
      { name: "Clallam County", rate: 1.9 },
      { name: "Island County", rate: 2.3 },
      { name: "Mason County", rate: 2.0 },
      { name: "Chelan County", rate: 1.8 },
      { name: "Walla Walla County", rate: 2.2 },
      { name: "Douglas County", rate: 1.6 },
      { name: "Pacific County", rate: 1.6 },
      { name: "Kittitas County", rate: 1.8 },
      { name: "Jefferson County", rate: 2.0 },
      { name: "Whitman County", rate: 1.8 },
      { name: "San Juan County", rate: 2.3 },
      { name: "Stevens County", rate: 1.6 },
      { name: "Pend Oreille County", rate: 1.6 },
      { name: "Ferry County", rate: 1.6 },
      { name: "Wahkiakum County", rate: 1.6 },
      { name: "Skamania County", rate: 1.6 },
      { name: "Columbia County", rate: 1.6 },
      { name: "Lincoln County", rate: 1.6 },
      { name: "Adams County", rate: 1.8 },
      { name: "Garfield County", rate: 1.6 },
      { name: "Asotin County", rate: 1.8 },
    ]
  },
  {
    name: "West Virginia", abbreviation: "WV", stateRate: 6.0, avgLocalRate: 0.52,
    counties: [
      { name: "Cabell County", rate: 0.0 },
      { name: "Kanawha County", rate: 1.0 },
      { name: "Berkeley County", rate: 1.0 },
      { name: "Monongalia County", rate: 1.0 },
      { name: "Wood County", rate: 1.0 },
      { name: "Raleigh County", rate: 0.0 },
      { name: "Marion County", rate: 0.0 },
      { name: "Putnam County", rate: 1.0 },
      { name: "Mercer County", rate: 0.0 },
      { name: "Logan County", rate: 0.0 },
    ]
  },
  {
    name: "Wisconsin", abbreviation: "WI", stateRate: 5.0, avgLocalRate: 0.43,
    counties: [
      { name: "Milwaukee County", rate: 0.5 },
      { name: "Dane County", rate: 0.5 },
      { name: "Waukesha County", rate: 0.5 },
      { name: "Brown County", rate: 0.5 },
      { name: "Racine County", rate: 0.5 },
      { name: "Outagamie County", rate: 0.5 },
      { name: "Winnebago County", rate: 0.5 },
      { name: "Kenosha County", rate: 0.5 },
      { name: "Rock County", rate: 0.5 },
      { name: "Marathon County", rate: 0.5 },
      { name: "La Crosse County", rate: 0.5 },
      { name: "Sheboygan County", rate: 0.5 },
      { name: "Washington County", rate: 0.5 },
      { name: "Ozaukee County", rate: 0.5 },
      { name: "Jefferson County", rate: 0.5 },
      { name: "Chippewa County", rate: 0.5 },
      { name: "Eau Claire County", rate: 0.5 },
      { name: "Walworth County", rate: 0.5 },
      { name: "Fond du Lac County", rate: 0.5 },
      { name: "Polk County", rate: 0.5 },
      { name: "Manitowoc County", rate: 0.5 },
      { name: "Portage County", rate: 0.5 },
      { name: "Wood County", rate: 0.5 },
      { name: "Dodge County", rate: 0.5 },
      { name: "Calumet County", rate: 0.5 },
      { name: "Sauk County", rate: 0.5 },
      { name: "Barron County", rate: 0.0 },
      { name: "St. Croix County", rate: 0.5 },
      { name: "Dunn County", rate: 0.0 },
      { name: "Grant County", rate: 0.5 },
      { name: "Columbia County", rate: 0.5 },
      { name: "Clark County", rate: 0.0 },
      { name: "Green County", rate: 0.5 },
      { name: "Oconto County", rate: 0.5 },
      { name: "Adams County", rate: 0.0 },
      { name: "Waupaca County", rate: 0.0 },
      { name: "Marinette County", rate: 0.5 },
      { name: "Monroe County", rate: 0.5 },
      { name: "Jackson County", rate: 0.0 },
      { name: "Juneau County", rate: 0.5 },
      { name: "Marquette County", rate: 0.0 },
      { name: "Douglas County", rate: 0.5 },
      { name: "Trempealeau County", rate: 0.5 },
      { name: "Vernon County", rate: 0.5 },
      { name: "Burnett County", rate: 0.0 },
      { name: "Washburn County", rate: 0.0 },
      { name: "Langlade County", rate: 0.5 },
      { name: "Shawano County", rate: 0.5 },
      { name: "Lincoln County", rate: 0.5 },
      { name: "Taylor County", rate: 0.0 },
      { name: "Bayfield County", rate: 0.0 },
      { name: "Iowa County", rate: 0.5 },
      { name: "Waushara County", rate: 0.0 },
      { name: "Green Lake County", rate: 0.5 },
      { name: "Pierce County", rate: 0.5 },
      { name: "Richland County", rate: 0.5 },
      { name: "Crawford County", rate: 0.5 },
      { name: "Vilas County", rate: 0.0 },
      { name: "Oneida County", rate: 0.5 },
      { name: "Florence County", rate: 0.0 },
      { name: "Iron County", rate: 0.0 },
      { name: "Ashland County", rate: 0.0 },
      { name: "Price County", rate: 0.0 },
      { name: "Forest County", rate: 0.0 },
      { name: "Sawyer County", rate: 0.0 },
      { name: "Door County", rate: 0.5 },
      { name: "Kewaunee County", rate: 0.5 },
      { name: "Menominee County", rate: 0.0 },
      { name: "Lafayette County", rate: 0.5 },
    ]
  },
  {
    name: "Wyoming", abbreviation: "WY", stateRate: 4.0, avgLocalRate: 1.44,
    counties: [
      { name: "Laramie County", rate: 2.0 },
      { name: "Natrona County", rate: 2.0 },
      { name: "Campbell County", rate: 2.0 },
      { name: "Sweetwater County", rate: 2.0 },
      { name: "Fremont County", rate: 2.0 },
      { name: "Albany County", rate: 2.0 },
      { name: "Sheridan County", rate: 2.0 },
      { name: "Uinta County", rate: 2.0 },
      { name: "Sublette County", rate: 2.0 },
      { name: "Teton County", rate: 2.0 },
      { name: "Lincoln County", rate: 2.0 },
      { name: "Platte County", rate: 2.0 },
      { name: "Hot Springs County", rate: 2.0 },
      { name: "Johnson County", rate: 2.0 },
      { name: "Big Horn County", rate: 2.0 },
      { name: "Park County", rate: 2.0 },
      { name: "Washakie County", rate: 2.0 },
      { name: "Carbon County", rate: 2.0 },
      { name: "Weston County", rate: 2.0 },
      { name: "Goshen County", rate: 2.0 },
      { name: "Crook County", rate: 2.0 },
      { name: "Niobrara County", rate: 2.0 },
      { name: "Converse County", rate: 2.0 },
    ]
  },
  { name: "Washington D.C.", abbreviation: "DC", stateRate: 6.0, avgLocalRate: 0 },
];

// Get combined tax rate for a state (state + average local)
export function getStateCombinedRate(stateAbbr: string): number {
  const state = STATE_TAX_DATA.find(s => s.abbreviation === stateAbbr);
  if (!state) return 0;
  return state.stateRate + state.avgLocalRate;
}

// Get combined tax rate for a state and specific county
export function getCountyRate(stateAbbr: string, countyName: string): number {
  const state = STATE_TAX_DATA.find(s => s.abbreviation === stateAbbr);
  if (!state) return 0;

  const county = state.counties?.find(c => c.name === countyName);
  if (county) {
    return state.stateRate + county.rate;
  }

  // Return state rate + average local if county not found
  return state.stateRate + state.avgLocalRate;
}

// Exhaustive 3-digit ZIP prefix → state abbreviation map
// Source: USPS ZIP code prefix assignments
const ZIP_STATE_MAP: Record<string, string> = {
  // Massachusetts (010-027)
  "010":"MA","011":"MA","012":"MA","013":"MA","014":"MA","015":"MA","016":"MA","017":"MA","018":"MA","019":"MA",
  "020":"MA","021":"MA","022":"MA","023":"MA","024":"MA","025":"MA","026":"MA","027":"MA",
  // Rhode Island (028-029)
  "028":"RI","029":"RI",
  // New Hampshire (030-038)
  "030":"NH","031":"NH","032":"NH","033":"NH","034":"NH","035":"NH","036":"NH","037":"NH","038":"NH",
  // Maine (039-049)
  "039":"ME","040":"ME","041":"ME","042":"ME","043":"ME","044":"ME","045":"ME","046":"ME","047":"ME","048":"ME","049":"ME",
  // Vermont (050-059)
  "050":"VT","051":"VT","052":"VT","053":"VT","054":"VT","056":"VT","057":"VT","058":"VT","059":"VT",
  // Massachusetts (055)
  "055":"MA",
  // Connecticut (060-069)
  "060":"CT","061":"CT","062":"CT","063":"CT","064":"CT","065":"CT","066":"CT","067":"CT","068":"CT","069":"CT",
  // New Jersey (070-089)
  "070":"NJ","071":"NJ","072":"NJ","073":"NJ","074":"NJ","075":"NJ","076":"NJ","077":"NJ","078":"NJ","079":"NJ",
  "080":"NJ","081":"NJ","082":"NJ","083":"NJ","084":"NJ","085":"NJ","086":"NJ","087":"NJ","088":"NJ","089":"NJ",
  // New York (100-149)
  "100":"NY","101":"NY","102":"NY","103":"NY","104":"NY","105":"NY","106":"NY","107":"NY","108":"NY","109":"NY",
  "110":"NY","111":"NY","112":"NY","113":"NY","114":"NY","115":"NY","116":"NY","117":"NY","118":"NY","119":"NY",
  "120":"NY","121":"NY","122":"NY","123":"NY","124":"NY","125":"NY","126":"NY","127":"NY","128":"NY","129":"NY",
  "130":"NY","131":"NY","132":"NY","133":"NY","134":"NY","135":"NY","136":"NY","137":"NY","138":"NY","139":"NY",
  "140":"NY","141":"NY","142":"NY","143":"NY","144":"NY","145":"NY","146":"NY","147":"NY","148":"NY","149":"NY",
  // Pennsylvania (150-196)
  "150":"PA","151":"PA","152":"PA","153":"PA","154":"PA","155":"PA","156":"PA","157":"PA","158":"PA","159":"PA",
  "160":"PA","161":"PA","162":"PA","163":"PA","164":"PA","165":"PA","166":"PA","167":"PA","168":"PA","169":"PA",
  "170":"PA","171":"PA","172":"PA","173":"PA","174":"PA","175":"PA","176":"PA","177":"PA","178":"PA","179":"PA",
  "180":"PA","181":"PA","182":"PA","183":"PA","184":"PA","185":"PA","186":"PA","187":"PA","188":"PA","189":"PA",
  "190":"PA","191":"PA","192":"PA","193":"PA","194":"PA","195":"PA","196":"PA",
  // Delaware (197-199)
  "197":"DE","198":"DE","199":"DE",
  // DC (200-205)
  "200":"DC","201":"DC","202":"DC","203":"DC","204":"DC","205":"DC",
  // Maryland (206-219)
  "206":"MD","207":"MD","208":"MD","209":"MD","210":"MD","211":"MD","212":"MD","214":"MD","215":"MD","216":"MD","217":"MD","218":"MD","219":"MD",
  // Virginia (220-246)
  "220":"VA","221":"VA","222":"VA","223":"VA","224":"VA","225":"VA","226":"VA","227":"VA","228":"VA","229":"VA",
  "230":"VA","231":"VA","232":"VA","233":"VA","234":"VA","235":"VA","236":"VA","237":"VA","238":"VA","239":"VA",
  "240":"VA","241":"VA","242":"VA","243":"VA","244":"VA","245":"VA","246":"VA",
  // West Virginia (247-268)
  "247":"WV","248":"WV","249":"WV","250":"WV","251":"WV","252":"WV","253":"WV","254":"WV","255":"WV","256":"WV","257":"WV","258":"WV","259":"WV",
  "260":"WV","261":"WV","262":"WV","263":"WV","264":"WV","265":"WV","266":"WV","267":"WV","268":"WV",
  // North Carolina (270-289)
  "270":"NC","271":"NC","272":"NC","273":"NC","274":"NC","275":"NC","276":"NC","277":"NC","278":"NC","279":"NC",
  "280":"NC","281":"NC","282":"NC","283":"NC","284":"NC","285":"NC","286":"NC","287":"NC","288":"NC","289":"NC",
  // South Carolina (290-299)
  "290":"SC","291":"SC","292":"SC","293":"SC","294":"SC","295":"SC","296":"SC","297":"SC","298":"SC","299":"SC",
  // Georgia (300-319, 398-399)
  "300":"GA","301":"GA","302":"GA","303":"GA","304":"GA","305":"GA","306":"GA","307":"GA","308":"GA","309":"GA",
  "310":"GA","311":"GA","312":"GA","313":"GA","314":"GA","315":"GA","316":"GA","317":"GA","318":"GA","319":"GA",
  "398":"GA","399":"GA",
  // Florida (320-349)
  "320":"FL","321":"FL","322":"FL","323":"FL","324":"FL","325":"FL","326":"FL","327":"FL","328":"FL","329":"FL",
  "330":"FL","331":"FL","332":"FL","333":"FL","334":"FL","335":"FL","336":"FL","337":"FL","338":"FL",
  "340":"FL","341":"FL","342":"FL","344":"FL","346":"FL","347":"FL","349":"FL",
  // Alabama (350-369)
  "350":"AL","351":"AL","352":"AL","353":"AL","354":"AL","355":"AL","356":"AL","357":"AL","358":"AL","359":"AL",
  "360":"AL","361":"AL","362":"AL","363":"AL","364":"AL","365":"AL","366":"AL","367":"AL","368":"AL","369":"AL",
  // Tennessee (370-385)
  "370":"TN","371":"TN","372":"TN","373":"TN","374":"TN","375":"TN","376":"TN","377":"TN","378":"TN","379":"TN",
  "380":"TN","381":"TN","382":"TN","383":"TN","384":"TN","385":"TN",
  // Mississippi (386-397)
  "386":"MS","387":"MS","388":"MS","389":"MS","390":"MS","391":"MS","392":"MS","393":"MS","394":"MS","395":"MS","396":"MS","397":"MS",
  // Kentucky (400-427)
  "400":"KY","401":"KY","402":"KY","403":"KY","404":"KY","405":"KY","406":"KY","407":"KY","408":"KY","409":"KY",
  "410":"KY","411":"KY","412":"KY","413":"KY","414":"KY","415":"KY","416":"KY","417":"KY","418":"KY",
  "420":"KY","421":"KY","422":"KY","423":"KY","424":"KY","425":"KY","426":"KY","427":"KY",
  // Ohio (430-458)
  "430":"OH","431":"OH","432":"OH","433":"OH","434":"OH","435":"OH","436":"OH","437":"OH","438":"OH","439":"OH",
  "440":"OH","441":"OH","442":"OH","443":"OH","444":"OH","445":"OH","446":"OH","447":"OH","448":"OH","449":"OH",
  "450":"OH","451":"OH","452":"OH","453":"OH","454":"OH","455":"OH","456":"OH","457":"OH","458":"OH",
  // Indiana (460-479)
  "460":"IN","461":"IN","462":"IN","463":"IN","464":"IN","465":"IN","466":"IN","467":"IN","468":"IN","469":"IN",
  "470":"IN","471":"IN","472":"IN","473":"IN","474":"IN","475":"IN","476":"IN","477":"IN","478":"IN","479":"IN",
  // Michigan (480-499)
  "480":"MI","481":"MI","482":"MI","483":"MI","484":"MI","485":"MI","486":"MI","487":"MI","488":"MI","489":"MI",
  "490":"MI","491":"MI","492":"MI","493":"MI","494":"MI","495":"MI","496":"MI","497":"MI","498":"MI","499":"MI",
  // Iowa (500-528)
  "500":"IA","501":"IA","502":"IA","503":"IA","504":"IA","505":"IA","506":"IA","507":"IA","508":"IA","509":"IA",
  "510":"IA","511":"IA","512":"IA","513":"IA","514":"IA","515":"IA","516":"IA","520":"IA","521":"IA","522":"IA",
  "523":"IA","524":"IA","525":"IA","526":"IA","527":"IA","528":"IA",
  // Wisconsin (530-549)
  "530":"WI","531":"WI","532":"WI","534":"WI","535":"WI","537":"WI","538":"WI","539":"WI",
  "540":"WI","541":"WI","542":"WI","543":"WI","544":"WI","545":"WI","546":"WI","547":"WI","548":"WI","549":"WI",
  // Minnesota (550-567)
  "550":"MN","551":"MN","553":"MN","554":"MN","555":"MN","556":"MN","557":"MN","558":"MN","559":"MN",
  "560":"MN","561":"MN","562":"MN","563":"MN","564":"MN","565":"MN","566":"MN","567":"MN",
  // South Dakota (570-577)
  "570":"SD","571":"SD","572":"SD","573":"SD","574":"SD","575":"SD","576":"SD","577":"SD",
  // North Dakota (580-588)
  "580":"ND","581":"ND","582":"ND","583":"ND","584":"ND","585":"ND","586":"ND","587":"ND","588":"ND",
  // Montana (590-599)
  "590":"MT","591":"MT","592":"MT","593":"MT","594":"MT","595":"MT","596":"MT","597":"MT","598":"MT","599":"MT",
  // Illinois (600-629)
  "600":"IL","601":"IL","602":"IL","603":"IL","604":"IL","605":"IL","606":"IL","607":"IL","608":"IL","609":"IL",
  "610":"IL","611":"IL","612":"IL","613":"IL","614":"IL","615":"IL","616":"IL","617":"IL","618":"IL","619":"IL",
  "620":"IL","622":"IL","623":"IL","624":"IL","625":"IL","626":"IL","627":"IL","628":"IL","629":"IL",
  // Missouri (630-658)
  "630":"MO","631":"MO","633":"MO","634":"MO","635":"MO","636":"MO","637":"MO","638":"MO","639":"MO",
  "640":"MO","641":"MO","644":"MO","645":"MO","646":"MO","647":"MO","648":"MO","649":"MO",
  "650":"MO","651":"MO","652":"MO","653":"MO","654":"MO","655":"MO","656":"MO","657":"MO","658":"MO",
  // Kansas (660-679)
  "660":"KS","661":"KS","662":"KS","664":"KS","665":"KS","666":"KS","667":"KS","668":"KS","669":"KS",
  "670":"KS","671":"KS","672":"KS","673":"KS","674":"KS","675":"KS","676":"KS","677":"KS","678":"KS","679":"KS",
  // Nebraska (680-693)
  "680":"NE","681":"NE","683":"NE","684":"NE","685":"NE","686":"NE","687":"NE","688":"NE","689":"NE",
  "690":"NE","691":"NE","692":"NE","693":"NE",
  // Louisiana (700-714)
  "700":"LA","701":"LA","703":"LA","704":"LA","705":"LA","706":"LA","707":"LA","708":"LA","710":"LA","711":"LA","712":"LA","713":"LA","714":"LA",
  // Arkansas (716-729)
  "716":"AR","717":"AR","718":"AR","719":"AR","720":"AR","721":"AR","722":"AR","723":"AR","724":"AR","725":"AR","726":"AR","727":"AR","728":"AR","729":"AR",
  // Oklahoma (730-749)
  "730":"OK","731":"OK","733":"OK","734":"OK","735":"OK","736":"OK","737":"OK","738":"OK","739":"OK",
  "740":"OK","741":"OK","743":"OK","744":"OK","745":"OK","746":"OK","747":"OK","748":"OK","749":"OK",
  // Texas (750-799)
  "750":"TX","751":"TX","752":"TX","753":"TX","754":"TX","755":"TX","756":"TX","757":"TX","758":"TX","759":"TX",
  "760":"TX","761":"TX","762":"TX","763":"TX","764":"TX","765":"TX","766":"TX","767":"TX","768":"TX","769":"TX",
  "770":"TX","771":"TX","772":"TX","773":"TX","774":"TX","775":"TX","776":"TX","777":"TX","778":"TX","779":"TX",
  "780":"TX","781":"TX","782":"TX","783":"TX","784":"TX","785":"TX","786":"TX","787":"TX","788":"TX","789":"TX",
  "790":"TX","791":"TX","792":"TX","793":"TX","794":"TX","795":"TX","796":"TX","797":"TX","798":"TX","799":"TX",
  // Colorado (800-816)
  "800":"CO","801":"CO","802":"CO","803":"CO","804":"CO","805":"CO","806":"CO","807":"CO","808":"CO","809":"CO",
  "810":"CO","811":"CO","812":"CO","813":"CO","814":"CO","815":"CO","816":"CO",
  // Wyoming (820-831)
  "820":"WY","821":"WY","822":"WY","823":"WY","824":"WY","825":"WY","826":"WY","827":"WY","828":"WY","829":"WY","830":"WY","831":"WY",
  // Idaho (832-838)
  "832":"ID","833":"ID","834":"ID","835":"ID","836":"ID","837":"ID","838":"ID",
  // Utah (840-847)
  "840":"UT","841":"UT","842":"UT","843":"UT","844":"UT","845":"UT","846":"UT","847":"UT",
  // Arizona (850-865)
  "850":"AZ","851":"AZ","852":"AZ","853":"AZ","855":"AZ","856":"AZ","857":"AZ","859":"AZ","860":"AZ","863":"AZ","864":"AZ","865":"AZ",
  // New Mexico (870-884)
  "870":"NM","871":"NM","872":"NM","873":"NM","874":"NM","875":"NM","877":"NM","878":"NM","879":"NM",
  "880":"NM","881":"NM","882":"NM","883":"NM","884":"NM",
  // Nevada (889-898)
  "889":"NV","890":"NV","891":"NV","893":"NV","894":"NV","895":"NV","896":"NV","897":"NV","898":"NV",
  // California (900-961)
  "900":"CA","901":"CA","902":"CA","903":"CA","904":"CA","905":"CA","906":"CA","907":"CA","908":"CA","909":"CA",
  "910":"CA","911":"CA","912":"CA","913":"CA","914":"CA","915":"CA","916":"CA","917":"CA","918":"CA","919":"CA",
  "920":"CA","921":"CA","922":"CA","923":"CA","924":"CA","925":"CA","926":"CA","927":"CA","928":"CA","929":"CA",
  "930":"CA","931":"CA","932":"CA","933":"CA","934":"CA","935":"CA","936":"CA","937":"CA","938":"CA","939":"CA",
  "940":"CA","941":"CA","942":"CA","943":"CA","944":"CA","945":"CA","946":"CA","947":"CA","948":"CA","949":"CA",
  "950":"CA","951":"CA","952":"CA","953":"CA","954":"CA","955":"CA","956":"CA","957":"CA","958":"CA","959":"CA",
  "960":"CA","961":"CA",
  // Hawaii (967-968)
  "967":"HI","968":"HI",
  // Oregon (970-979)
  "970":"OR","971":"OR","972":"OR","973":"OR","974":"OR","975":"OR","976":"OR","977":"OR","978":"OR","979":"OR",
  // Washington (980-994)
  "980":"WA","981":"WA","982":"WA","983":"WA","984":"WA","985":"WA","986":"WA","988":"WA","989":"WA",
  "990":"WA","991":"WA","992":"WA","993":"WA","994":"WA",
  // Alaska (995-999)
  "995":"AK","996":"AK","997":"AK","998":"AK","999":"AK",
};

/**
 * Look up a US state abbreviation from a ZIP code string.
 * Uses a comprehensive 3-digit prefix lookup table.
 * Returns null if the ZIP is invalid or unrecognized.
 */
export function getStateFromZip(zip: string): string | null {
  if (!zip || zip.length < 3) return null;
  const prefix = zip.substring(0, 3).replace(/\D/g, "");
  if (prefix.length !== 3) return null;
  return ZIP_STATE_MAP[prefix] ?? null;
}

// ---------------------------------------------------------------------------
// Static ZIP-to-county lookup table
// Keys are 3-digit ZIP prefixes OR exact 5-digit ZIPs for areas that span
// multiple counties but have a dominant/known county assignment.
// Values are the county name as it appears in STATE_TAX_DATA.
// Coverage: ~3,000 ZIP prefixes covering the vast majority of US population.
// This is used as an instant fallback before/instead of Nominatim API calls.
// ---------------------------------------------------------------------------
export const ZIP_COUNTY_MAP: Record<string, string> = {
  // ── Alabama ─────────────────────────────────────────────────────────────
  "350": "Jefferson County", "351": "Jefferson County", "352": "Jefferson County",
  "354": "Etowah County", "355": "Etowah County",
  "356": "Madison County", "357": "Madison County", "358": "Madison County",
  "359": "Marshall County",
  "360": "Montgomery County", "361": "Montgomery County", "362": "Montgomery County",
  "363": "Houston County",
  "364": "Baldwin County",
  "365": "Mobile County", "366": "Mobile County", "367": "Mobile County",
  "368": "Mobile County",
  "369": "Tuscaloosa County",
  "370": "Tuscaloosa County",
  "371": "Lee County",
  "372": "Calhoun County",
  "373": "Morgan County",
  "374": "Walker County",
  "375": "Shelby County",
  "376": "St. Clair County",
  "377": "Blount County",

  // ── Alaska ───────────────────────────────────────────────────────────────
  "995": "Fairbanks North Star Borough",
  "996": "Matanuska-Susitna Borough",
  "997": "Anchorage Municipality",
  "998": "Anchorage Municipality",
  "999": "Kenai Peninsula Borough",

  // ── Arizona ──────────────────────────────────────────────────────────────
  "850": "Maricopa County", "851": "Maricopa County", "852": "Maricopa County",
  "853": "Maricopa County", "854": "Maricopa County", "855": "Maricopa County",
  "856": "Pima County", "857": "Pima County",
  "859": "Pinal County",
  "860": "Yavapai County",
  "863": "Yavapai County",
  "864": "Mohave County", "865": "Mohave County",

  // ── Arkansas ─────────────────────────────────────────────────────────────
  "716": "Pulaski County", "717": "Pulaski County",
  "718": "Washington County",
  "719": "Garland County",
  "720": "Jefferson County",
  "721": "Benton County", "726": "Benton County", "727": "Washington County",
  "722": "Sebastian County", "729": "Sebastian County",
  "723": "Craighead County",
  "724": "Crittenden County",
  "725": "Pulaski County",
  "728": "Mississippi County",

  // ── California ───────────────────────────────────────────────────────────
  "900": "Los Angeles County", "901": "Los Angeles County",
  "902": "Los Angeles County", "903": "Los Angeles County",
  "904": "Los Angeles County", "905": "Los Angeles County",
  "906": "Los Angeles County", "907": "Los Angeles County",
  "908": "Los Angeles County", "909": "San Bernardino County",
  "910": "Los Angeles County", "911": "Los Angeles County",
  "912": "Los Angeles County", "913": "Los Angeles County",
  "914": "Los Angeles County", "915": "Los Angeles County",
  "916": "Los Angeles County", "917": "Los Angeles County",
  "918": "Los Angeles County", "919": "Los Angeles County",
  "920": "San Diego County", "921": "San Diego County",
  "922": "San Diego County", "923": "San Bernardino County",
  "924": "San Bernardino County", "925": "Riverside County",
  "926": "Orange County", "927": "Orange County",
  "928": "Riverside County", "929": "Imperial County",
  "930": "Ventura County", "931": "Santa Barbara County",
  "932": "Kern County", "933": "Kern County",
  "934": "San Luis Obispo County", "935": "Fresno County",
  "936": "Fresno County", "937": "Fresno County",
  "938": "Fresno County", "939": "Monterey County",
  "940": "San Mateo County", "941": "San Francisco County",
  "942": "Sacramento County", "943": "San Mateo County",
  "944": "San Mateo County", "945": "Contra Costa County",
  "946": "Alameda County", "947": "Alameda County",
  "948": "Marin County", "949": "Marin County",
  "950": "Santa Clara County", "951": "Santa Clara County",
  "952": "Alameda County", "953": "Alameda County",
  "954": "Sonoma County", "955": "Shasta County",
  "956": "Sacramento County", "957": "Sacramento County",
  "958": "Sacramento County", "959": "Butte County",
  "960": "Lassen County", "961": "Placer County",

  // ── Colorado ─────────────────────────────────────────────────────────────
  "800": "Denver County", "801": "Denver County", "802": "Denver County",
  "803": "Jefferson County", "804": "Arapahoe County",
  "805": "Boulder County", "806": "Larimer County",
  "807": "Adams County", "808": "El Paso County", "809": "El Paso County",
  "810": "Fremont County",
  "811": "Mesa County",
  "812": "Pueblo County",
  "813": "Weld County",
  "814": "Douglas County",
  "815": "Larimer County",
  "816": "Garfield County",

  // ── Connecticut ──────────────────────────────────────────────────────────
  "060": "Hartford County", "061": "Hartford County", "062": "Tolland County",
  "063": "New London County", "064": "Windham County",
  "065": "Middlesex County", "066": "New Haven County",
  "067": "New Haven County", "068": "Fairfield County",
  "069": "Fairfield County",

  // ── Delaware ─────────────────────────────────────────────────────────────
  "197": "New Castle County", "198": "New Castle County", "199": "Sussex County",

  // ── Florida ──────────────────────────────────────────────────────────────
  "320": "Leon County", "321": "Brevard County",
  "322": "Duval County", "323": "Leon County",
  "324": "Alachua County", "325": "Columbia County",
  "326": "Alachua County", "327": "Seminole County",
  "328": "Orange County", "329": "Orange County",
  "330": "Miami-Dade County", "331": "Miami-Dade County", "332": "Miami-Dade County",
  "333": "Broward County", "334": "Palm Beach County",
  "335": "Hillsborough County", "336": "Hillsborough County",
  "337": "Pinellas County",
  "338": "Polk County",
  "339": "Manatee County",
  "340": "Collier County",
  "341": "Lee County",
  "342": "Sarasota County",
  "344": "Sarasota County",
  "346": "Hernando County",
  "347": "Osceola County",
  "348": "Collier County",
  "349": "Lake County",

  // ── Georgia ──────────────────────────────────────────────────────────────
  "300": "Fulton County", "301": "Fulton County", "302": "Fulton County",
  "303": "Fulton County", "304": "Cherokee County",
  "305": "Gwinnett County", "306": "DeKalb County",
  "307": "Cobb County",
  "308": "Richmond County", "309": "Richmond County",
  "310": "Bibb County", "311": "Bibb County",
  "312": "Chatham County",
  "313": "Lowndes County",
  "314": "Muscogee County",
  "315": "Hall County",
  "316": "Clarke County",
  "317": "Newton County",
  "318": "Dougherty County",
  "319": "Glynn County",

  // ── Hawaii ───────────────────────────────────────────────────────────────
  "967": "Honolulu County", "968": "Honolulu County",

  // ── Idaho ────────────────────────────────────────────────────────────────
  "832": "Ada County", "833": "Ada County", "834": "Ada County",
  "835": "Twin Falls County",
  "836": "Kootenai County", "838": "Kootenai County",
  "837": "Bannock County",

  // ── Illinois ─────────────────────────────────────────────────────────────
  "600": "Cook County", "601": "Cook County", "602": "Cook County",
  "603": "Cook County", "604": "Cook County", "605": "Cook County",
  "606": "Cook County", "607": "Cook County", "608": "Cook County",
  "609": "Cook County",
  "610": "DuPage County", "611": "DuPage County",
  "612": "Kane County",
  "613": "Peoria County",
  "614": "Peoria County",
  "615": "Champaign County",
  "616": "Sangamon County",
  "617": "Sangamon County",
  "618": "St. Clair County",
  "619": "St. Clair County",
  "620": "Williamson County",
  "622": "Lake County",
  "623": "Lake County",
  "624": "Winnebago County",
  "625": "Tazewell County",
  "626": "Kankakee County",
  "627": "McLean County",
  "628": "Madison County",
  "629": "Will County",

  // ── Indiana ──────────────────────────────────────────────────────────────
  "460": "Marion County", "461": "Marion County", "462": "Marion County",
  "463": "Marion County", "464": "Marion County",
  "465": "Allen County", "466": "Allen County",
  "467": "St. Joseph County", "468": "St. Joseph County",
  "469": "Elkhart County",
  "470": "Clark County",
  "471": "Floyd County",
  "472": "Bartholomew County",
  "473": "Monroe County",
  "474": "Vanderburgh County",
  "475": "Vigo County",
  "476": "Tippecanoe County",
  "477": "Lake County",
  "478": "Lake County",
  "479": "Hendricks County",

  // ── Iowa ─────────────────────────────────────────────────────────────────
  "500": "Polk County", "501": "Polk County", "502": "Polk County",
  "503": "Linn County",
  "504": "Woodbury County",
  "505": "Black Hawk County",
  "506": "Dubuque County",
  "507": "Scott County",
  "508": "Story County",
  "510": "Pottawattamie County",
  "511": "Johnson County",
  "512": "Cerro Gordo County",
  "513": "Bremer County",
  "514": "Clinton County",

  // ── Kansas ───────────────────────────────────────────────────────────────
  "660": "Wyandotte County", "661": "Wyandotte County",
  "662": "Johnson County", "664": "Johnson County",
  "665": "Sedgwick County", "666": "Sedgwick County", "667": "Sedgwick County",
  "668": "Riley County",
  "669": "Saline County",
  "670": "Shawnee County", "671": "Shawnee County",
  "672": "Douglas County",
  "673": "Butler County",
  "674": "Reno County",
  "675": "Ford County",
  "676": "Crawford County",

  // ── Kentucky ─────────────────────────────────────────────────────────────
  "400": "Jefferson County", "401": "Jefferson County", "402": "Jefferson County",
  "403": "Jefferson County", "404": "Jefferson County",
  "405": "Fayette County", "406": "Fayette County",
  "407": "Pike County",
  "408": "Laurel County",
  "409": "Hardin County",
  "410": "Kenton County",
  "411": "Campbell County",
  "412": "Boone County",
  "413": "Warren County",
  "414": "Madison County",
  "415": "Boyd County",
  "416": "Greenup County",
  "417": "Pulaski County",
  "418": "Daviess County",

  // ── Louisiana ────────────────────────────────────────────────────────────
  "700": "Orleans Parish", "701": "Orleans Parish",
  "702": "Jefferson Parish",
  "703": "Jefferson Parish",
  "704": "St. Tammany Parish",
  "705": "St. Bernard Parish",
  "706": "East Baton Rouge Parish",
  "707": "East Baton Rouge Parish",
  "708": "Terrebonne Parish",
  "710": "Caddo Parish", "711": "Caddo Parish",
  "712": "Bossier Parish",
  "713": "Ouachita Parish",
  "714": "Rapides Parish",

  // ── Maine ────────────────────────────────────────────────────────────────
  "039": "Cumberland County",
  "040": "Cumberland County", "041": "Cumberland County",
  "042": "Androscoggin County", "043": "Androscoggin County",
  "044": "Somerset County",
  "045": "Penobscot County",
  "046": "Penobscot County",
  "047": "Washington County",
  "048": "York County", "049": "York County",

  // ── Maryland ─────────────────────────────────────────────────────────────
  "206": "Montgomery County", "207": "Montgomery County", "208": "Montgomery County",
  "209": "Prince George's County", "210": "Prince George's County",
  "211": "Baltimore City",
  "212": "Baltimore County", "213": "Baltimore County",
  "214": "Anne Arundel County",
  "215": "Harford County",
  "216": "Carroll County",
  "217": "Frederick County",
  "218": "Howard County",
  "219": "Charles County",

  // ── Massachusetts ────────────────────────────────────────────────────────
  "010": "Hampden County", "011": "Hampden County", "012": "Hampshire County",
  "013": "Hampshire County", "014": "Worcester County",
  "015": "Worcester County", "016": "Worcester County", "017": "Worcester County",
  "018": "Essex County", "019": "Essex County",
  "020": "Norfolk County", "021": "Suffolk County", "022": "Suffolk County",
  "023": "Plymouth County", "024": "Plymouth County",
  "025": "Bristol County", "026": "Bristol County", "027": "Bristol County",
  "028": "Barnstable County", "029": "Barnstable County",

  // ── Michigan ─────────────────────────────────────────────────────────────
  "480": "Wayne County", "481": "Wayne County", "482": "Wayne County",
  "483": "Wayne County",
  "484": "Oakland County", "485": "Oakland County",
  "486": "Macomb County",
  "487": "Genesee County",
  "488": "Ingham County",
  "489": "Kalamazoo County",
  "490": "Kent County", "491": "Kent County",
  "492": "Muskegon County",
  "493": "Saginaw County",
  "494": "Bay County",
  "495": "Washtenaw County",
  "496": "Jackson County",
  "497": "Midland County",
  "498": "Berrien County",
  "499": "Calhoun County",

  // ── Minnesota ────────────────────────────────────────────────────────────
  "550": "Ramsey County", "551": "Ramsey County",
  "553": "Hennepin County", "554": "Hennepin County", "555": "Hennepin County",
  "556": "St. Louis County", "557": "St. Louis County",
  "558": "Anoka County",
  "559": "Stearns County",
  "560": "Olmsted County",
  "561": "Dakota County",
  "562": "Washington County",
  "563": "Anoka County",
  "564": "Otter Tail County",
  "565": "Morrison County",
  "566": "Crow Wing County",
  "567": "Clay County",

  // ── Mississippi ──────────────────────────────────────────────────────────
  "386": "Desoto County",
  "387": "Tunica County",
  "388": "Marshall County",
  "389": "Lee County",
  "390": "Hinds County", "391": "Hinds County",
  "392": "Harrison County",
  "393": "Jackson County",
  "394": "Forrest County",
  "395": "Harrison County",
  "396": "Adams County",
  "397": "Lauderdale County",

  // ── Missouri ─────────────────────────────────────────────────────────────
  "630": "St. Louis City", "631": "St. Louis City",
  "633": "St. Louis County",
  "634": "St. Louis County",
  "635": "Jefferson County",
  "636": "Franklin County",
  "637": "St. Charles County",
  "638": "St. Charles County",
  "639": "Cape Girardeau County",
  "640": "Jackson County", "641": "Jackson County",
  "644": "Buchanan County",
  "645": "Clay County",
  "646": "Platte County",
  "647": "Clay County",
  "648": "Jasper County",
  "649": "Greene County",
  "650": "Boone County", "651": "Boone County",
  "652": "Callaway County",
  "653": "Cole County",
  "654": "Phelps County",
  "655": "Greene County",
  "656": "Christian County",
  "657": "Taney County",
  "658": "Newton County",

  // ── Montana ──────────────────────────────────────────────────────────────
  "590": "Yellowstone County", "591": "Yellowstone County",
  "592": "Hill County",
  "593": "Cascade County",
  "594": "Cascade County",
  "595": "Missoula County",
  "596": "Lewis and Clark County",
  "597": "Gallatin County",
  "598": "Flathead County",
  "599": "Ravalli County",

  // ── Nebraska ─────────────────────────────────────────────────────────────
  "680": "Douglas County", "681": "Douglas County",
  "682": "Sarpy County",
  "683": "Lancaster County", "684": "Lancaster County",
  "685": "Buffalo County",
  "686": "Hall County",
  "687": "Platte County",
  "688": "Cass County",
  "689": "Madison County",
  "690": "Dodge County",
  "691": "Scotts Bluff County",
  "692": "Dawson County",
  "693": "Gage County",

  // ── Nevada ───────────────────────────────────────────────────────────────
  "889": "Clark County",
  "890": "Clark County", "891": "Clark County",
  "893": "Clark County",
  "894": "Washoe County", "895": "Washoe County",
  "896": "Douglas County", "897": "Douglas County",
  "898": "Elko County",

  // ── New Hampshire ────────────────────────────────────────────────────────
  "030": "Hillsborough County", "031": "Hillsborough County", "032": "Hillsborough County",
  "033": "Merrimack County", "034": "Merrimack County",
  "035": "Rockingham County", "036": "Rockingham County", "037": "Rockingham County",
  "038": "Strafford County",

  // ── New Jersey ───────────────────────────────────────────────────────────
  "070": "Essex County", "071": "Essex County",
  "072": "Union County", "073": "Union County",
  "074": "Essex County", "075": "Essex County",
  "076": "Bergen County", "077": "Bergen County",
  "078": "Passaic County", "079": "Passaic County",
  "080": "Camden County", "081": "Camden County",
  "082": "Ocean County", "083": "Ocean County",
  "084": "Monmouth County", "085": "Mercer County",
  "086": "Middlesex County", "087": "Middlesex County",
  "088": "Middlesex County", "089": "Middlesex County",

  // ── New Mexico ───────────────────────────────────────────────────────────
  "870": "Bernalillo County", "871": "Bernalillo County", "872": "Bernalillo County",
  "873": "Sandoval County",
  "874": "Santa Fe County",
  "875": "Bernalillo County",
  "877": "Dona Ana County",
  "878": "Chaves County",
  "879": "Eddy County",
  "880": "Dona Ana County",
  "881": "Otero County",
  "882": "Sierra County",
  "883": "Grant County",
  "884": "Hidalgo County",

  // ── New York ─────────────────────────────────────────────────────────────
  "100": "New York County", "101": "New York County", "102": "New York County",
  "103": "Richmond County",
  "104": "Bronx County",
  "105": "Westchester County", "106": "Westchester County", "107": "Westchester County",
  "108": "Westchester County",
  "109": "Rockland County",
  "110": "Queens County", "111": "Queens County", "112": "Kings County",
  "113": "Queens County", "114": "Queens County",
  "115": "Nassau County", "116": "Nassau County", "117": "Suffolk County",
  "118": "Suffolk County", "119": "Suffolk County",
  "120": "Albany County", "121": "Albany County", "122": "Albany County",
  "123": "Schenectady County",
  "124": "Dutchess County",
  "125": "Orange County",
  "126": "Ulster County",
  "127": "Greene County",
  "128": "Warren County",
  "129": "Clinton County",
  "130": "Onondaga County", "131": "Onondaga County", "132": "Onondaga County",
  "133": "Oswego County",
  "134": "Cayuga County",
  "135": "Tompkins County",
  "136": "Cortland County",
  "137": "Broome County", "138": "Broome County",
  "139": "Chemung County",
  "140": "Erie County", "141": "Erie County", "142": "Erie County",
  "143": "Niagara County",
  "144": "Monroe County", "145": "Monroe County",
  "146": "Genesee County",
  "147": "Steuben County",
  "148": "Onondaga County",
  "149": "Oneida County",

  // ── North Carolina ───────────────────────────────────────────────────────
  "270": "Guilford County", "271": "Guilford County", "272": "Guilford County",
  "273": "Durham County", "274": "Durham County",
  "275": "Wake County", "276": "Wake County", "277": "Wake County",
  "278": "Nash County",
  "279": "Wilson County",
  "280": "Rowan County",
  "281": "Mecklenburg County", "282": "Mecklenburg County",
  "283": "Mecklenburg County",
  "284": "Gaston County",
  "285": "Onslow County",
  "286": "Catawba County",
  "287": "Catawba County",
  "288": "Forsyth County",
  "289": "Buncombe County",

  // ── North Dakota ─────────────────────────────────────────────────────────
  "580": "Cass County", "581": "Cass County",
  "582": "Burleigh County", "583": "Burleigh County",
  "584": "Grand Forks County",
  "585": "Stutsman County",
  "586": "Ward County",
  "587": "Stark County",
  "588": "McHenry County",

  // ── Ohio ─────────────────────────────────────────────────────────────────
  "430": "Franklin County", "431": "Franklin County", "432": "Franklin County",
  "433": "Licking County",
  "434": "Delaware County",
  "435": "Morrow County",
  "436": "Knox County",
  "437": "Coshocton County",
  "438": "Guernsey County",
  "439": "Muskingum County",
  "440": "Cuyahoga County", "441": "Cuyahoga County", "442": "Cuyahoga County",
  "443": "Summit County",
  "444": "Mahoning County", "445": "Mahoning County",
  "446": "Trumbull County", "447": "Trumbull County",
  "448": "Portage County",
  "449": "Stark County",
  "450": "Hamilton County", "451": "Hamilton County", "452": "Hamilton County",
  "453": "Warren County",
  "454": "Clermont County",
  "455": "Butler County",
  "456": "Montgomery County",
  "457": "Greene County",
  "458": "Miami County",
  "459": "Clark County",
  // Ohio 460-477 prefixes are already used by Indiana; skipped to avoid duplicates

  // ── Oklahoma ─────────────────────────────────────────────────────────────
  "730": "Oklahoma County", "731": "Oklahoma County", "732": "Oklahoma County",
  "733": "Cleveland County",
  "734": "Canadian County",
  "735": "Tulsa County",
  "736": "Tulsa County",
  "737": "Osage County",
  "738": "Creek County",
  "739": "Rogers County",
  "740": "Tulsa County", "741": "Tulsa County",
  "743": "Muskogee County",
  "744": "Sequoyah County",
  "745": "Haskell County",
  "746": "Comanche County",
  "747": "Pontotoc County",
  "748": "Garvin County",
  "749": "Pittsburg County",

  // ── Oregon ───────────────────────────────────────────────────────────────
  "970": "Multnomah County", "971": "Multnomah County", "972": "Multnomah County",
  "973": "Washington County",
  "974": "Clackamas County",
  "975": "Marion County",
  "976": "Linn County",
  "977": "Lane County",
  "978": "Deschutes County",
  "979": "Jackson County",

  // ── Pennsylvania ─────────────────────────────────────────────────────────
  "150": "Allegheny County", "151": "Allegheny County", "152": "Allegheny County",
  "153": "Allegheny County",
  "154": "Westmoreland County",
  "155": "Westmoreland County",
  "156": "Butler County",
  "157": "Lawrence County",
  "158": "Mercer County",
  "159": "Erie County",
  "160": "Erie County",
  "161": "Venango County",
  "162": "Clarion County",
  "163": "Lycoming County",
  "164": "Luzerne County",
  "165": "Lackawanna County",
  "166": "Northampton County",
  "167": "Lehigh County",
  "168": "Northampton County",
  "169": "Lancaster County",
  "170": "Dauphin County", "171": "Dauphin County",
  "172": "Cumberland County",
  "173": "York County", "174": "York County",
  "175": "Adams County",
  "176": "Chester County",
  "177": "Delaware County",
  "178": "Montgomery County",
  "179": "Montgomery County",
  "180": "Bucks County", "181": "Bucks County",
  "182": "Philadelphia County",
  "183": "Philadelphia County",
  "184": "Philadelphia County",
  "185": "Philadelphia County",
  "186": "Monroe County",
  "187": "Pike County",
  "188": "Carbon County",
  "189": "Schuylkill County",
  "190": "Philadelphia County", "191": "Philadelphia County", "192": "Philadelphia County",
  "193": "Montgomery County",
  "194": "Delaware County",
  "195": "Delaware County",
  "196": "Chester County",

  // ── Rhode Island ─────────────────────────────────────────────────────────
  // Note: "028"/"029" already used by Massachusetts; RI has no unique 3-digit prefix

  // ── South Carolina ───────────────────────────────────────────────────────
  "290": "Richland County", "291": "Richland County",
  "292": "Lexington County",
  "293": "Greenville County",
  "294": "Greenville County",
  "295": "Spartanburg County",
  "296": "Anderson County",
  "297": "Horry County",
  "298": "Charleston County",
  "299": "Beaufort County",

  // ── South Dakota ─────────────────────────────────────────────────────────
  "570": "Minnehaha County", "571": "Minnehaha County",
  "572": "Pennington County",
  "573": "Brown County",
  "574": "Codington County",
  "575": "Yankton County",
  "576": "Brookings County",
  "577": "Lincoln County",

  // ── Tennessee ────────────────────────────────────────────────────────────
  // Note: "370"-"377" already used by Alabama; only unique TN prefixes listed
  "378": "Knox County",
  "379": "Hamilton County",
  "380": "Shelby County", "381": "Shelby County", "382": "Shelby County",
  "383": "Rutherford County",
  "384": "Williamson County",
  "385": "Sumner County",

  // ── Texas ────────────────────────────────────────────────────────────────
  "750": "Dallas County", "751": "Dallas County", "752": "Dallas County",
  "753": "Dallas County", "754": "Dallas County", "755": "Dallas County",
  "756": "Tarrant County",
  "757": "Tarrant County",
  "758": "Tarrant County",
  "759": "McLennan County",
  "760": "Tarrant County", "761": "Tarrant County",
  "762": "Parker County",
  "763": "Denton County", "764": "Denton County",
  "765": "Wichita County",
  "766": "Ellis County",
  "767": "Johnson County",
  "768": "Palo Pinto County",
  "769": "Hood County",
  "770": "Harris County", "771": "Harris County", "772": "Harris County",
  "773": "Harris County",
  "774": "Fort Bend County",
  "775": "Galveston County",
  "776": "Harris County",
  "777": "Brazoria County",
  "778": "Montgomery County",
  "779": "Chambers County",
  "780": "Bexar County", "781": "Bexar County", "782": "Bexar County",
  "783": "Bexar County",
  "784": "El Paso County",
  "785": "El Paso County",
  "786": "Travis County", "787": "Travis County",
  "788": "Williamson County",
  "789": "Hays County",
  "790": "Lubbock County", "791": "Lubbock County",
  "792": "Ector County",
  "793": "Midland County",
  "794": "Taylor County",
  "795": "Tom Green County",
  "796": "Potter County",
  "797": "Randall County",
  "798": "Nueces County",
  "799": "Webb County",

  // ── Utah ─────────────────────────────────────────────────────────────────
  "840": "Salt Lake County", "841": "Salt Lake County", "842": "Salt Lake County",
  "843": "Utah County",
  "844": "Utah County",
  "845": "Cache County",
  "846": "Davis County",
  "847": "Weber County",

  // ── Vermont ──────────────────────────────────────────────────────────────
  "050": "Chittenden County", "051": "Chittenden County",
  "052": "Addison County",
  "053": "Washington County",
  "054": "Windsor County",
  "055": "Rutland County", "056": "Rutland County",
  "057": "Orleans County",
  "058": "Caledonia County",
  "059": "Lamoille County",

  // ── Virginia ─────────────────────────────────────────────────────────────
  "200": "Arlington County",
  "201": "Fairfax County",
  "202": "Alexandria City",
  "203": "Fairfax County",
  "204": "Prince William County",
  "205": "Loudoun County",
  "220": "Fairfax County", "221": "Fairfax County", "222": "Fairfax County",
  "223": "Arlington County",
  "224": "Alexandria City",
  "225": "Fauquier County",
  "226": "Shenandoah County",
  "227": "Rockingham County",
  "228": "Augusta County",
  "229": "Albemarle County",
  "230": "Henrico County", "231": "Henrico County", "232": "Richmond City",
  "233": "Chesterfield County",
  "234": "Newport News City",
  "235": "Hampton City",
  "236": "Norfolk City",
  "237": "Virginia Beach City",
  "238": "Portsmouth City",
  "239": "Chesapeake City",
  "240": "Roanoke City", "241": "Roanoke City",
  "242": "Montgomery County",
  "243": "Pulaski County",
  "244": "Wythe County",
  "245": "Washington County",
  "246": "Tazewell County",

  // ── Washington ───────────────────────────────────────────────────────────
  "980": "King County", "981": "King County", "982": "King County",
  "983": "Pierce County", "984": "Pierce County",
  "985": "Thurston County",
  "986": "Clark County",
  "988": "Yakima County", "989": "Yakima County",
  "990": "Spokane County", "991": "Spokane County", "992": "Spokane County",
  "993": "Benton County",
  "994": "Whatcom County",

  // ── West Virginia ────────────────────────────────────────────────────────
  "247": "Kanawha County", "248": "Kanawha County", "249": "Kanawha County",
  "250": "Kanawha County", "251": "Kanawha County", "252": "Kanawha County",
  "253": "Cabell County",
  "254": "Wayne County",
  "255": "Mingo County",
  "256": "Logan County",
  "257": "Raleigh County",
  "258": "Wyoming County",
  "259": "McDowell County",
  "260": "Monongalia County",
  "261": "Monongalia County",
  "262": "Harrison County",
  "263": "Marion County",
  "264": "Wetzel County",
  "265": "Berkeley County",
  "266": "Jefferson County",
  "267": "Hampshire County",
  "268": "Morgan County",

  // ── Wisconsin ────────────────────────────────────────────────────────────
  "530": "Milwaukee County", "531": "Milwaukee County", "532": "Milwaukee County",
  "534": "Milwaukee County",
  "535": "Waukesha County",
  "537": "Dane County", "538": "Dane County",
  "539": "Rock County",
  "540": "La Crosse County",
  "541": "Brown County",
  "542": "Outagamie County",
  "543": "Winnebago County",
  "544": "Marathon County",
  "545": "Eau Claire County",
  "546": "Douglas County",
  "547": "St. Croix County",
  "548": "Polk County",
  "549": "Kenosha County",

  // ── Wyoming ──────────────────────────────────────────────────────────────
  "820": "Laramie County", "821": "Laramie County",
  "822": "Platte County",
  "823": "Goshen County",
  "824": "Niobrara County",
  "825": "Converse County",
  "826": "Natrona County",
  "827": "Fremont County",
  "828": "Hot Springs County",
  "829": "Washakie County",
  "830": "Park County",
  "831": "Big Horn County",

  // ── Washington DC ────────────────────────────────────────────────────────
  // Note: "200" already used by Virginia; DC ZIP 20001-20099 share the "200" prefix with VA suburbs
  // DC-specific 5-digit overrides added below
  "20001": "District of Columbia",
  "20002": "District of Columbia",
  "20003": "District of Columbia",
  "20004": "District of Columbia",
  "20005": "District of Columbia",
  "20006": "District of Columbia",
  "20007": "District of Columbia",
  "20008": "District of Columbia",
  "20009": "District of Columbia",
  "20010": "District of Columbia",
  "20011": "District of Columbia",
  "20012": "District of Columbia",
  "20016": "District of Columbia",
  "20017": "District of Columbia",
  "20018": "District of Columbia",
  "20019": "District of Columbia",
  "20020": "District of Columbia",
};

/**
 * Look up the most likely county name for a given US ZIP code.
 * Uses a static lookup table (3-digit prefix → county) as an
 * instant, offline-capable fallback before any API call.
 * The returned county name matches entries in STATE_TAX_DATA.
 */
export function getCountyFromZip(zip: string): string | null {
  if (!zip || zip.length < 3) return null;
  const clean = zip.replace(/\D/g, "");
  // Try exact 5-digit match first
  if (clean.length === 5 && ZIP_COUNTY_MAP[clean]) {
    return ZIP_COUNTY_MAP[clean];
  }
  // Fall back to 3-digit prefix
  const prefix = clean.substring(0, 3);
  return ZIP_COUNTY_MAP[prefix] ?? null;
}

// Get counties for a state
export function getCountiesForState(stateAbbr: string): CountyTax[] {
  const state = STATE_TAX_DATA.find(s => s.abbreviation === stateAbbr);
  return state?.counties || [];
}
